### ISSUE TITLE
TraceZ zpage is broken for spans names with characters that require url encoding

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1425]
**Describe the bug**
The tracez zpage does not work correctly with span names that contain characters that require url encoding.

**Steps to reproduce**
Create a sample with spans called "/users/{id}/address" and "my span name with spaces in it". Run the app, go to the tracez page, click on the links to samples of those spans.

**What did you expect to see?**
The page to render the span names, and show the sampled spans in the details section at the bottom

**What did you see instead?**
The span name is mangled, with url-coded characters in it. No sampled spans are displayed.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-sdk-extension-zpages
Version: 0.7.0-SNAPSHOT
How did you reference these artifacts? (excerpt from your `build.gradle`, `pom.xml`, etc)
I built the project locally and referenced them from my build.gradle.

**Environment**
Compiler: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
OS: MacOSX v.10.14.6 (Mojave)
Runtime (if different from JDK above): same as above
OS (if different from OS compiled on): same as above

**Additional context**
None

**Comment by williamhu99** [comment]
I removed the `URLEncoder` from `TracezZPageHandler` and built a sample app locally, and everything seems to be running fine. I'm a little concerned because I initially added the `URLEncoder` due to this [comment](https://github.com/open-telemetry/opentelemetry-java/pull/1380#issuecomment-655100658). Based on this, it seems that the spaces aren't actually being changed to +'s. I'll create a pull request, so you can verify if this is true on your end.

**Comment by jkwatson** [comment]
I'm pretty sure this is fixed now. closing.
