### ISSUE TITLE
two traceparent headers are not rejected

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java#1676]
Next w3c context propagation tests fails:

```
def test_traceparent_duplicated(self):
		'''
		harness sends a request with two traceparent headers
		expects a valid traceparent from the output header, with a newly generated trace_id
		'''
		traceparent, tracestate = self.make_single_request_and_get_tracecontext([
			['traceparent', '00-12345678901234567890123456789011-1234567890123456-01'],
			['traceparent', '00-12345678901234567890123456789012-1234567890123456-01'],
		])
		self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789011')
		self.assertNotEqual(traceparent.trace_id.hex(), '12345678901234567890123456789012')
```

Got in #1653
Can be reproduced by running tests from mentioned PR

**Comment by malafeev** [comment]
not a bug, it's an issue of an extractor. 
Extractor should check that there are more than one header with the same key.
Some frameworks can return first header.

**Comment by iNikem** [comment]
Wait, we still need to fix "an issue of an extractor", no?

**Comment by Oberon00** [comment]
We need to fix an issue of the getter API first if we want to fix this in the extractor https://github.com/open-telemetry/opentelemetry-specification/issues/433

**Comment by malafeev** [comment]
custom extractor can check multi-value header and return joined string instead of first found value.

**Comment by jkwatson** [comment]
This is still a bug in the overall handling of the W3C headers, though, isn't it, @malafeev ? I don't think this should be closed until it's working to spec, no matter where the issue lies.

**Comment by malafeev** [comment]
ok

**Comment by jkwatson** [comment]
Note: you have to run at STRICT=2 to see this error (and a couple of others)

**Comment by jkwatson** [comment]
@malafeev This test passes for me on the main branch, and I see the extractor concatenates the headers with a comma between them. 

Now that I have dug into the issue, I understand more of what you were saying. I think that this bug should be closed, because our W3C TraceContext implementation works to spec (in this instance at least). If someone's extractor is throwing data away, our HttpTraceContext implementation shouldn't be held to account. 

If we need to change the extractor/getter interface to allow more than one header, then that's a totally separate issue, and not this one. :)

**Comment by jkwatson** [comment]
Closing, as not-a-bug. Sorry for the confusion, @malafeev !
