### ISSUE TITLE
Examples should be built in CI to ensure they aren't broken when users try them

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1686]
Since examples are in a separate Gradle project, we don't build them on CI. We should since if they're broken, users will be surprised.

/cc @codeboten

**Comment by thisthat** [comment]
there has been already some discussion on this: https://github.com/open-telemetry/opentelemetry-java/pull/695#discussion_r361801981

**Comment by jkwatson** [comment]
I think switching to non-snapshot at this point for the examples is a good idea. We're getting close to GA, and I think our examples should be more stable going forward. And, so, building them on CI seems like a small enhancement, since once it's done, it shouldn't change until the next version is released.

**Comment by jkwatson** [comment]
Now that we've hit 1.0.0, our examples *MUST* be backwards compatible (for non-alpha modules), so I'll put in a PR that makes a change for that.
