### ISSUE TITLE
Allow setting Kind on a span directly instead of via a Builder

### ISSUE THREAD

**Issue by marcingrzejszczak** [open-telemetry/opentelemetry-java#1793]
Brave treats Spans as quite mutable objects where a Kind can be set on it at any time. I see that OTel requires going via a builder. What's the reasoning behind not being able to mutate a kind of a span?

The use case is that you can have a generic injector and extractor from headers that doesn't know whether it's related to messaging or http. Then the kind differs and you could set it on a created span instead of passing on a builder that has to be then manipulated.

**Comment by arminru** [comment]
Hi @marcingrzejszczak,
this is defined in the OTel specification here: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span-creation
If you'd like to discuss changing this, it would make sense to create an issue there.

As far as I know, it's defined at time of span creation because span  kind is an argument to samplers and sampling decisions are made on span start, thus the span kind is not mutable afterwards. See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#sampler.

Note that one can defer starting a span at a later point of time by providing a custom start time stamp.

**Comment by marcingrzejszczak** [comment]
>  If you'd like to discuss changing this, it would make sense to create an issue there.

That's not necessary really cause I have an idea how to work this around by passing on a builder. I just wanted to know the rationale.
