### ISSUE TITLE
Add Context to SpanProcessor methods

### ISSUE THREAD

**Issue by parallelstream** [open-telemetry/opentelemetry-java#1811]
**Is your feature request related to a problem? Please describe.**
I would like to use information from Context (Baggage in particular) in SpanProcessor's methods. Currently SpanProcessor's methods don't take Context 

**Describe the solution you'd like**
```
public interface SpanProcessor {

  void onStart(Context ctx, ReadWriteSpan span);

  void onEnd(Context ctx, ReadableSpan span);
...
}
```

**Describe alternatives you've considered**
The only option is to rely on Context.current() in SpanProcessor which is not the right thing when in all cases - for example parent is explicitly set to the specific Context (and also, this will not work for e.g. Go version where there's no Context.current())

**Comment by jkwatson** [comment]
HI @parallelstream . 
In the main branch of the project, we already have the `onStart` signature that you are interested in.

If you want to change the `onEnd()`, that will require a specification change, as we'd want this to work the same in all languages. There is a related issue open in the specs right now: https://github.com/open-telemetry/opentelemetry-specification/issues/1089. I would recommend putting in your 2 cents on that one, to help move it in the direction you are interested in.

Thanks!

**Comment by parallelstream** [comment]
Thanks, @jkwatson. Right now I will be fine with just onStart() changes, but think at some stage we would come to the need of onEnd() taking context as well for exact same reasoning.
The issue you mentioned is about R/W span in onEnd, do you want me to bundle the Context there as well or would you recommend just opening a new issue in specification ?

**Comment by jkwatson** [comment]
I would go ahead and mention it, and your use-case in the discussion on that issue. I'm sure they'll tell you if they want to roll it in, or open a separate one. :)

**Comment by Oberon00** [comment]
@parallelstream Which Context do you want in onEnd? Also the parent context? Then we would need to store the context somewhere. In open-telemetry/opentelemetry-specification#875 that originally added this, I originally had specified to add the full parent Context to the span data, but that idea was shot down due to performance concerns (unfortunately in a Spec SIG meeting so there is not much documentation on the ticket: https://github.com/open-telemetry/opentelemetry-specification/pull/875#issuecomment-685659609). So IMHO: Instead of passing the context to OnEnd, we should either: add the parent Context to SpanData or leave it as-is with not require storing the parent Context.

**Comment by bogdandrutu** [comment]
@parallelstream closing this since the "End" call on the Span does not accept a context, because of this the only thing that the SDK can provide is the `Context.current()` which you can access as well if needed.

If we will add support for user to pass a different `Context` for end (which I am not sure why) we need to pass that to the processor.
