### ISSUE TITLE
Should Span.makeCurrent use parent context instead of current context

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#1939]
Is there a significant use case where having it use current context is better than parent? I think that change would help a lot with the confusion Marcin finds with our context extraction idiom.

**Comment by Oberon00** [comment]
This would mean that we have to store the full parent context with the span, which may be memory-heavy (since the parent context would contain a span, which would recursively contain a parent context which contains a span, etc.)

Also, what should happen for extracted spans? They do not have a parent context but *are* a parent context.

What is more, if I use `myBaggage.makeCurrent(); mySpan.makeCurrent()`, the baggage would not be current as it would have been replaced by the baggage that was active in the span's parent context.

Thus, I think the current solution is both straightforward to implement and think about.

**Comment by jkwatson** [comment]
> Also, what should happen for extracted spans? They do not have a parent context but are a parent context.

Not only extracted spans, but any misc. internal span that has no parent (like scheduled jobs and the like). 

I don't think changing the semantics of this method would make things easier to reason about; precisely the opposite. "parent context" isn't something that is universally meaningful, I don't think, where as "current context" certainly is.

**Comment by marcingrzejszczak** [comment]
The current solution is not straightforward to implement and think about. In my opinion the situation is quite the opposite.

OpenTelemetry is an extremely young project. I understand that it's focusing on the context however other, more mature projects do not focus on the context that much. If I'm working with tracing, I don't care about the context, I care about the span, the baggage, the trace. Context is completely irrelevant, it's an implementational detail. Please look at OpenZipkin Brave, an extremely well-known and widely used mature project and maybe try to find some inspiration there.

Now back to the problem. In OTel, for baggage to work I have to put a context in scope. The problem with putting it in scope is that other things happen when you put them in scope - MDC is accessed, other thread local entries are checked. We don't want that to always happen. So the first problem is that in order for me to call `Baggage.current()` or sth like that I always need to pass the scope. That's not a good idea in my opinion.

Let's imagine the following situation. Let's say that I have a span coming from context B whose parent is A. I understand that if A has baggage `foo=foo` and B has baggage `bar=bar`, then span should have access to `foo` and `bar` baggage entries. Currently in OTel, when I make `span.makeCurrent()` call, then I don't have access to `foo=foo` because it's a parent context. This is absurd. For that to work in Sleuth I needed to make terrible hacks with stacking up contexts (context B, its parent etc.) and then trying to read them back. It should be OTel's responsibility, not Sleuth's.

All in all I really think that this design decision is wrong and @anuraaga's suggestions should be taken into consideration more frequently. In Spring Cloud Sleuth we have quite a few users already using baggage and it would be a shame to tell the users that the baggage feature is faulty when using Sleuth with Baggage (also from my understanding almost nobody is really using this feature except for me so I'd be grateful for taking my suggestions into account).

**Comment by jkwatson** [comment]
@marcingrzejszczak Can you outline exactly how these 3 cases would use this suggestion?

In particular, for each of these cases, we need to consider propagation from outside the process, within the process and to an external process, for spans and baggage. Also, we must consider how metrics implementation will be able to access both spans and baggage during metric recordings.

1. Fully manual instrumentation, no auto-instrumentation in place. 
2. Auto-instrumentation, with manual instrumentation adding spans/baggage as needed.
3. Your use-case of bridging to another tracing API?

I'd like to see pseudocode for all of these cases, and be shown how it's universally better than what we have today. Also, it would be very helpful if you could come to the specification meetings where we are discussing all of these issues, so your particular use-case can be considered. If we're going to change the semantics of Span/Baggage/Metric Context interaction, it needs to be done universally across all of the supported OpenTelemetry languages.

I don't think it's that we're not taking @anuraaga's suggestions seriously. To the contrary! His input and opinions have been and continue to be incredibly useful and his influence on the project is already large.

**Comment by anuraaga** [comment]
> Not only extracted spans, but any misc. internal span that has no parent (like scheduled jobs and the like).

If there's no parent I think it could be just the root. Actually the Java instrumentation already does this during extraction - we always force root context to work around context propagation bugs in other instrumentation like Akka which may leave an unrelated context in scope. Hopefully we'll be able to debug these better soon :) But even then I don't know if we'd remove this behavior as a just in case guard.

`baggage.makeCurrent` followed by `span.makeCurrent` breaking is a convincing argument. But I wonder how common it is - I've never used baggage so don't know what common patterns are for it. So this issue is exploratory for what works best in common user code. I think coming up with those examples @jkwatson suggests would be a great exploration.

**Comment by jkwatson** [comment]
Is there a need to activate each context as it's created? Can't you just put both the span and the baggage in the context before activating it?

**Comment by marcingrzejszczak** [comment]
Hey @jkwatson, I'll answer the rest of the questions when I have some time, however regarding `Your use-case of bridging to another tracing API?`. Spring Cloud Sleuth *does not* bridge OpenTelemetry to Brave. OTel is a separate module, completely independent from Brave so I don't know what are you referring to.

**Comment by jkwatson** [comment]
> Hey @jkwatson, I'll answer the rest of the questions when I have some time, however regarding `Your use-case of bridging to another tracing API?`. Spring Cloud Sleuth _does not_ bridge OpenTelemetry to Brave. OTel is a separate module, completely independent from Brave so I don't know what are you referring to.

I'm sorry if my language wasn't precise. It seems like you have a different use-case from what we've considered, so if you want to give a better name for it, that would be fine.

**Comment by Oberon00** [comment]
@marcingrzejszczak 

> Context is completely irrelevant, it's an implementational detail. 

That's not true at all in OpenTelemetry. The `Context` type is a public type that appears in many places in the API, for example it is returned by `extract`  and the only way to override the default implicit parent span is by passing in a `Context`.

**Comment by marcingrzejszczak** [comment]
> I'm sorry if my language wasn't precise. It seems like you have a different use-case from what we've considered, so if you want to give a better name for it, that would be fine.

Sleuth has its own API that wraps instrumentations. That way you can use either Brave or OTel at the same time. I'm trying to create such API that is applicable to both (and presumably other tracer implementations).

> That's not true at all in OpenTelemetry. The Context type is a public type that appears in many places in the API, for example it is returned by extract and the only way to override the default implicit parent span is by passing in a Context.

I understand that it's a public type, however from the point of view of a user of e.g. tracing one cares about spans, traces, tags, events etc. not contexts. However, I understand that it's different in OTel. I'm not a maintainer of this project, I'm pretty sure you've got everything figured out and discussed and my suggestions will most likely be ignored - I accept that.

Anyways, I think I'll have to bend the new Sleuth API to start introducing concepts of scopes for baggage. That way if one creates baggage for OTel it will create a new context with baggage in it and it will be put in scope that the user will need to close (or use try-with-resources) and for Brave it will basically be a noop scope cause there's no need for a scope there. Also it seems that OTel's baggage is immutable so I can't simply change a value of a given entry - again I'll have to introduce a new scope each time I want to mutate baggage. Without these change Baggage will not be propagated between Sleuth apps which would make adding OTel to Sleuth pointless.

**Comment by iNikem** [comment]
It seems that I miss something important here. I have read this discussion two times and am still completely confused.

How can `Span.makeCurrent` us parent context? This method adds given span to a context and then activates the resulting new context. In what case does it make sense to add this span to some other context than the one active at the moment of calling `makeCurrent()`? `Span.makeCurrent() == Context.getCurrent().getParent().with(this).makeCurrent()`?? It seems nonsense. What do I miss? :)

**Comment by iNikem** [comment]
> Let's imagine the following situation. Let's say that I have a span coming from context B whose parent is A. I understand that if A has baggage `foo=foo` and B has baggage `bar=bar`, then span should have access to `foo` and `bar` baggage entries. Currently in OTel, when I make `span.makeCurrent()` call, then I don't have access to `foo=foo` because it's a parent context.

@marcingrzejszczak Do you mean the following situation?
```
  @Test
  void marcin(){
    Scope scopeA = Baggage.builder().put("foo", "foo").build().makeCurrent();
    Scope scopeB = Baggage.builder().put("bar", "bar").build().makeCurrent();
    Span span = tracer.spanBuilder("mySpan").startSpan();
    Scope spanScope = span.makeCurrent();

    assertThat(Baggage.current().getEntryValue("foo")).isEqualTo("foo");
    assertThat(Baggage.current().getEntryValue("bar")).isEqualTo("bar");

    spanScope.close();
    scopeB.close();
    scopeA.close();
  }
```

This test passes for me without any problems. Did I misunderstood your use-case?

**Comment by Oberon00** [comment]
@iNikem 
I think the parent context meant here is not the parent of the current context but the parent context of the span to be set (which we don't store at all currently).

**Comment by marcingrzejszczak** [comment]
@Oberon00 is right about my expectations. I understand that this is not feasible in OTel. I'll work this around in Sleuth, so we can close this issue as far as I'm concerned.

**Comment by jkwatson** [comment]
@anuraaga can we close this?
