### ISSUE TITLE
Should B3Propagator support X-B3-ParentSpanId?

### ISSUE THREAD

**Issue by daviddenton** [open-telemetry/opentelemetry-java#1947]
**Is your feature request related to a problem? Please describe.**
The [B3 propagation spec](https://github.com/openzipkin/b3-propagation#parentspanid) defines that the Parent Span Id is passed between services. This seems to be missing in the current B3 Propagator implementation. Not sure if am missing a reason that it's not there (am quite new to OpenTelemetry so possible it's irrelevant) or is just an oversight?

**Describe the solution you'd like**
Implement ParentSpanId propagation via X-B3-ParentSpanId header

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks for all your work on this project! 😄

**Comment by jkwatson** [comment]
Hi @daviddenton . Thanks for the issue submission.

This was discussed in the specs as a part of this PR:  https://github.com/open-telemetry/opentelemetry-specification/pull/1045

If you'd like to re-open that discussion, please do so over in the specs, since we wouldn't want java to be diverging from what's been specified. Thanks!

**Comment by jkwatson** [comment]
closing this, as it was decided in the specs not to support it at this time. We can create a new issue to track updating if the spec changes.
