### ISSUE TITLE
Consistent directory names

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#1951]
Everywhere outside examples we use `_` to separate between words (see initial PR https://github.com/open-telemetry/opentelemetry-java/pull/461) the main reason was that inside Google they enforce "_", so was making the life easier for Google people to import and use this project internally. In the examples we use `-` (see https://github.com/open-telemetry/opentelemetry-java/tree/master/examples/sdk-usage) for the same purpose.

I would suggest we stick with `_` to be nice with Google people that have to import and use this project inside Google (they will not consume the artifacts, they will have to import (clone) the code inside their repository so the directory names matter for them).

**Comment by anuraaga** [comment]
Consistency is good - I'd lean towards hyphens.

Even as a frequent user of this repo, I find myself always having to think twice to figure out a Gradle command because of the project name mangling. I've been wanting to consolidate on the instrumentation repo of not mangling the project name so commands follow directory structure which is intuitive. An alternative that preserves this property without name mangling is to have every folder name match the project name, which has some stuttering.

As long as that is kept, underscore being turned into hyphen in published artifacts is ok, but I think it would still provide a more natural contributor experience for this repo to have the hyphens in folder names to align better with the artifact names more than less. If Google's tool hasn't been already, I'm sure it could be fixed to deal with this fine.

**Comment by trask** [comment]
Just a data point: I found the underscores odd, hyphens are way more common in Java repos (in my experience)

**Comment by bogdandrutu** [comment]
@trask I agree if that is the case we should follow what the majority does.

**Comment by bogdandrutu** [comment]
@anuraaga with this proposal the directory will still not match the project name, and the issue is not aiming to achieve that. But if we resolve the dash vs underscore then we may get closer to that.
