### ISSUE TITLE
Remove 3rd party propagators from this repository

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#2067]
See recently merged spec PR: https://github.com/open-telemetry/opentelemetry-specification/pull/1144

**Comment by anuraaga** [comment]
For me, I've always felt like the `extension` folders in this repo are our version of a contrib repo - they used to even be called `contrib` before being renamed to `extension`. I guess we could choose from

1) Documenting that extensions are contrib and consider adding CODEOWNERS for the folders (this seems like a good idea already for the logging extension for example)
2) Move all the extensions to `opentelemetry-java-contrib`
3) Move only propagators to `opentelemetry-java-contrib`

Lean a bit towards 1) since it seems simpler

**Comment by jkwatson** [comment]
If we think 1) is still in the spirit of the spec, then I'm totally ok with it. @carlosalberto what do you think?

**Comment by carlosalberto** [comment]
The change in the Specification precisely mentions 'core repos', so I think this is a very liberal interpretation of it 😉 But ultimately the decision is yours @jkwatson about whether you want to support such code. Other SIG maintainers were not specially happy about maintaining such code, but if you are fine maintaining it (same repo, in the end), I'm definitely cool.

(If we decide to separate the OT one, I'm fine with moving it somewhere else and maintain it, btw).

**Comment by jkwatson** [comment]
If the owning vendors (@carlosalberto and @anuraaga ) are ok with "best effort" maintenance of the propagators, then I'm ok with it. I think we'd want to add some very clear verbiage to the READMEs for the propagators that makes it clear that critical bugs should be logged with the vendors themselves, with at least some kind of link to how to do that.

Otherwise, I wouldn't guess there's a lot of actual work to be done maintaining this code. And, if the owning vendors aren't satisfied with the service, they are absolutely free to move the code out to where they can provide the support they need to.

**Comment by carlosalberto** [comment]
@jkwatson Makes sense. Also we can apply what other maintainers suggested, about removing the related code in case the vendor doesn't help maintaining it (worst case). Sounds good?

**Comment by jkwatson** [comment]
> @jkwatson Makes sense. Also we can apply what other maintainers suggested, about removing the related code in case the vendor doesn't help maintaining it (worst case). Sounds good?

That sounds good to me, yes.

**Comment by breedx-splk** [comment]
I think this can be closed now, right?
