### ISSUE TITLE
Decide on cross-version compatibility requirement or not

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#2203]
We can either require all artifacts published from this repo to be aligned to the same version in a user's app or not. If the latter, we cannot share internal code among artifacts (for example, `TemporaryBuffers.java` is useful in API and in trace-propagators artifacts) or otherwise we would need to make sure we don't make breaking changes to them to prevent problems in the face of misaligned versions, eliminating any advantage of making them internal in the first place.

I think it's fairly conventional to expect all artifacts from a repo to be aligned, and we provide the BOM to make it easy. So it's probably reasonable for us to have a policy where all artifacts are aligned. Let me know any thoughts or concerns.

**Comment by anuraaga** [comment]
By the way, if yes on expecting alignment, I'll move the opentelemetry-api-internal all into common

**Comment by Oberon00** [comment]
Note that we need to fulfill https://github.com/open-telemetry/oteps/pull/143. In particular I am wondering if we can expect SDK and API versions to always align. If a library was compiled with API version 1.x but the app uses SDK + API version 1.y (x < y) that should normally not be a problem since at runtime, only the app's version would be used? And as long as 1.y is ABI compatible to 1.x, that should just work.

**Comment by jkwatson** [comment]
Yes, API and SDK versions should definitely *not* be required to be aligned. 
Yes, we should move everything in `opentelemetry-api-internal` into common.
I think it is reasonable to require all the SDK modules to be aligned, since that's intended to be something configured at the application level.

I think it will be impossible to require that versions of everything being used in the API be aligned, however. Imagine a world where OTel instrumentation is baked into libraries. Some of those libraries will instrument with spans, and some with metrics, and we can't require that they're using the same versions across transitive dependencies, since we don't control those dependencies.

@marcingrzejszczak decisions on this could impact you.

**Comment by marcingrzejszczak** [comment]
> I think it will be impossible to require that versions of everything being used in the API be aligned, however. Imagine a world where OTel instrumentation is baked into libraries. Some of those libraries will instrument with spans, and some with metrics, and we can't require that they're using the same versions across transitive dependencies, since we don't control those dependencies.

When you say aligned what do you mean exactly? Sleuth uses currently opentelemetry-instrumentation-java and opentelemetry-java. We must align on the opentelemetry-java version that means that we're using the same version in all of our modules. That version must be compatible with whatever opentelemety-instrumentation-java provides - otherwise our code breaks.

**Comment by Oberon00** [comment]
I'm also not quite sure about this API/SDK alignment: Even if libraries everywhere have the API "baked in", they do not actually vendor the API, so at runtime, there can always only be one version of the API. And then it might not be a stretch to require this single runtime version to be the same as the SDK version.

**Comment by jkwatson** [comment]
> I'm also not quite sure about this API/SDK alignment: Even if libraries everywhere have the API "baked in", they do not actually vendor the API, so at runtime, there can always only be one version of the API. And then it might not be a stretch to require this single runtime version to be the same as the SDK version.

I thought we explicitly didn't want to require the runtime API version to have to match the SDK. Although, I would expect this would happen most of the time, since the SDK dependency would pull in the matching API version transitively. Is this something we want to require, though? What if the instrumentation has a higher version of the API than the SDK being used & configured?

**Comment by marcingrzejszczak** [comment]
> I thought we explicitly didn't want to require the runtime API version to have to match the SDK. Although, I would expect this would happen most of the time, since the SDK dependency would pull in the matching API version transitively. Is this something we want to require, though? What if the instrumentation has a higher version of the API than the SDK being used & configured?

I can't imagine that there wouldn't be an OpenTelemetry Instrumentation that would not be compatible with the latest OpenTelemetry SDK and OpenTelemetry API. It's as if Spring Cloud wouldn't provide a release train that is compatible with the latest Spring Boot that is not compatible with the latest Spring Framework. As a OpenTelemetry consumer I would want to use OpenTelemetry Instrumentation version that gives me compatibility with the latest versions of OpenTelemetry parts.

**Comment by anuraaga** [comment]
@marcingrzejszczak By aligning, in practice I basically mean use the bom :) So all artifacts from this repo get aligned, but not instrumentation repo.

@jkwatson Yeah - as long as following semver, it should never be a problem to be using a higher version than a dependency. I think typically you just always want to be using a bom to have a version that's at least higher than the highest in dependencies. Using a lower version might be missing a new method.

I'm worried that if we talk about alignment only for within-API or within-SDK, it could get confusing compared to just aligning within this repo - and I guess it's relatively standard for large Java repos I've seen.

**Comment by marcingrzejszczak** [comment]
> @marcingrzejszczak By aligning, in practice I basically mean use the bom :) So all artifacts from this repo get aligned, but not instrumentation repo.

I fully agree. I'd want to use a BOM and not care about versions. That would be ideal.

> @jkwatson Yeah - as long as following semver, it should never be a problem to be using a higher version than a dependency. I think typically you just always want to be using a bom to have a version that's at least higher than the highest in dependencies. Using a lower version might be missing a new method.

Precisely. That's what we're doing in Spring. We provide BOMs but you can override each version (e.g. `-Dspring-cloud-sleuth.version=1.2.3`). It happened that we had to release a particular module separately from the release train.

> I'm worried that if we talk about alignment only for within-API or within-SDK, it could get confusing compared to just aligning within this repo - and I guess it's relatively standard for large Java repos I've seen.

IMO the alignment must be with SDK and API. Otherwise it makes no sense really.

>  but not instrumentation repo.

cc @trask - what's the OTel Instrumentation OTel API & OTel SDK support strategy? I understand that you'll support as many highest OTel API major versions as possible? So if there's OTel 1.x and 2.x you'll have 2 branches supporting OTel BOM 1.x and 2.x ? What is the ETA for a OTel instrumentation release following the OTel API & SDK release? 

From Sleuth perspective, since we're using OTel Instrumentation, SDK and API it would be best to use the BOM from the one that uses the rest (OTel instrumentation) and that BOM would set all the versions accordingly.

**Comment by jkwatson** [comment]
We're now discussing (in today's spec meeting) about the possibility of versioning the SDK separately from the API (in order to facilitate more rapid evolution of the SDK's interfaces). Does using a BOM allow for a mix-and-match approach to the set of versions in the dependencies, or do they all have to be the same version for everything?

For example, can I say "opentelemetry-bom:1.4" depends on "opentelemetry-api:1.0" and "opentelemetry-sdk:1.3" (as a simplified example)?

**Comment by trask** [comment]
> So if there's OTel 1.x and 2.x you'll have 2 branches supporting OTel BOM 1.x and 2.x

Yes

> What is the ETA for a OTel instrumentation release following the OTel API & SDK release?

We generally make an instrumentation release within a week (+/-) of an API release. Prior to 1.0, we are following the same version number as the API. But when the API hits 1.0, we will probably still be versioning instrumentation releases as 0.x for some time until the `opentelemetry-instrumentation-api` artifact is considered API-stable.

**Comment by jkwatson** [comment]
I think we can close this now that we have a solid versioning story in place. Please re-open if you feel what we have is not adequate.
