### ISSUE TITLE
OpenTelemetry 0.14.1 JAR has manifest with Implementation-Title "all"

### ISSUE THREAD

**Issue by quijote** [open-telemetry/opentelemetry-java#2549]
MANIFEST.MF of opentelemetry-api-0.14.1.jar looks like this:

    Manifest-Version: 1.0
    Implementation-Title: all
    Implementation-Version: 0.14.1
    Built-By: runner
    Built-JDK: 11.0.9
    Source-Compatibility: 1.8
    Target-Compatibility: 1.8
    Automatic-Module-Name: io.opentelemetry.api

I think Implementation-Title should be improved here. Some tools rely on information provided by manifest. Previous versions of the the jar used value "opentelemetry-api".

**Comment by Oberon00** [comment]
Maybe related to the same workaround that was causing #2511

**Comment by anuraaga** [comment]
Hey I think this is simple to fix but curious what are you using the information for? The only real documentation I can find is this

https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html

Where it is set to java.util.

Since we already have the module name, I'm considering removing the Implementation-Title since it looks redundant and not commonly used.

**Comment by quijote** [comment]
We use the information in monitoring to show which library versions are used by an application. 

Most JAR files I have encountered in maven or elsewhere have a manifest with proper Implementation-Title and Implementation-Version. I think it would be a bit odd to have version without title. But yes, in general tools may also be able to use Automatic-Module-Name as a fallback if Implementation-Title is missing or not useful. I will do this for now to detect usage of OpenTelemetry 0.14.x.
