### ISSUE TITLE
Document setTraceConfig methods

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2627]
Right now the SdkTracerProviderBuilder accepts a `Supplier<TraceConfig> traceConfigSupplier` for the configuration supplier. This may be dangerous because no clear explanation about thread-safetyness and for the performance impact this may have on the application if too slow.

Possible solution:
* Do nothing and pray to God that users will not shot themself in the foot;
* Document clearly the potential impact and requirements for this supplier;
* Avoid calling user code, implement the logic of changing the active TraceConfig in the SDK (this logic was implemented and changed).

**Comment by anuraaga** [comment]
It's interesting we do have some documentation for IdGenerator, but can't find anything for `SpanProcessor`, `Clock`, and presumably many classes. I think we need a swap of the entire documentation for issues like this, and consistency of formatting, etc.

**Comment by bogdandrutu** [comment]
I started to read the javadoc that's why I filed all these issues

**Comment by jkwatson** [comment]
I looked through the code around this, and, luckily, a given span gets a single `TraceConfig` object for its entire lifetime, which is very good. 

The only place that this is exposed is on the `getActiveTraceConfig()` method, which I'm wondering if we actually need to expose any more. [also note: our Jaeger remote sampler docs are out of date]. 

So, yes, this supplier is called on the hot path, once per span. At the bare minimum, we should very strongly document this fact, so that implementors can be aware of possible performance impacts to this being a slow call (for instance, you really wouldn't want this to make a remote call!). 

And, to everybody's point... there are extension points that are on the hot path, and we should make that clear when it is the case.

**Comment by anuraaga** [comment]
We should extend the javadoc

- `setTraceConfig(TraceConfig)` with an example of the code it is a shortcut for
- `setTraceConfig(Supplier)` explaining the requirements for this supplier such as returning a config quickly, and being threadsafe.
