### ISSUE TITLE
Update javadoc for ParentBased methods

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2632]
Currently there are 2 methods to create ParentBased samplers, one that directly creates the Sampler without allowing to set other options and one that returns the builder.

I would suggest to remove the optimization method that does not return the builder. It is an extra public method to maintain and returning a builder in Java world is probably one of the most common patter so nothing to worry.

**Comment by anuraaga** [comment]
Parent-based sampling is normal sampling, it's very important that it's easy to create parent-based samplers (it's already too bad users will be confused by the default factories not being parent-based). And the builder has several very confusingly named methods which even those experienced in tracing likely don't understand easily - hiding this advanced API as much as possible is another good side effect of the `create` method. The builder is the overoptimization here really ;) But we're stuck with it since it's in the spec, I don't expect much usage for it though.

**Comment by anuraaga** [comment]
We found the javadoc for `parentBasedBuilder` to be incorrectly talking about behavior when it should be configuration. And let's update the javadoc for `parentBased` (and any other similar shortcuts) to provide a `@code` example of what it is a shortcut for.
