### ISSUE TITLE
Document samplers package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2644]
Right now we have in the same package as the main SDK components:
* IdsGenerator
* SpanProcessor

In a `config` package:
* Configs only for span limits

In a `sampler` package:
* Sampler interface and few implementations

I think `data` and `export` are very clear what they are and those don't need to change.

Questions:
* Should we move Sampler and Config to the main SDK components package for consistency?
* If not, why do we not move IdsGenerator separately?

**Comment by anuraaga** [comment]
I think the main reason Sampler is in a package is because there are many different implementations, and will likely be more implementations. It's a growing package, and I don't see a reason it's less clear for it to be separate than data / exporter.

IdGenerator is just ever going to have one implementation which is probably why it isn't in a package. Separating it into a package could be ok. Moving TraceConfig up would also be ok and could be grouped with renaming it - that's what I'd lean towrads..

**Comment by bogdandrutu** [comment]
So moving the TraceConfig is probably a good thing anyway and as you mention renaming in the same time is great.

For the Sampler I am not sure if we should worry about implementations, because most of them will be extensions not in the SDK.

**Comment by jkwatson** [comment]
My opinion: I'm fine with moving TraceConfig up and renaming it (also the javadoc in there needs to be updated...it references unused/unsupported system properties from a bygone era). The rest I would keep as-is due mostly to the fact that there is a bunch of stuff in there that all belongs together and makes sense to have separated.

**Comment by anuraaga** [comment]
Samplers are an extension point with significant complexity and different use cases so separating them out for a package can allow users to focus on them to deep dive. We can take advantage of this by adding even more detailed documentation to `package-info.java`, documenting various use cases, with code samples, for configuring sampling for the SDK.
