### ISSUE TITLE
Should we return the interface or the object in static methods like `getInstance`?

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2658]
In the trace propagator we return the interface:
https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/trace/propagation/W3CTraceContextPropagator.html

In the baggage propagator we return the implementation class:
https://www.javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.html

We need to be consistent and return always one or the other. I am in favor of returning the implementation class so in the future if we add extra methods on the implementation class those will be exposed.

**Comment by anuraaga** [comment]
Yeah let's return implementation, if a class is public there's no reason to not expose it in factories too and can add flexibility.

**Comment by Oberon00** [comment]
> We need to be consistent

Why? I would return the interface unless the class has additional public methods.

**Comment by bogdandrutu** [comment]
> I would return the interface unless the class has additional public methods.

Then you lock yourself for the future. You cannot change the return type (ABI breaking change) so even if you add more additional methods you will not be able to expose them.

**Comment by jkwatson** [comment]
I would generally favor returning the more restrictive type, in this case being the interface, since it exposes a little bit less API surface. 

But, I don't feel incredibly strong about it, and can see both sides of the argument, so if @bogdandrutu and @anuraaga agree on the approach, I'll go along with for the ride.

**Comment by anuraaga** [comment]
@jkwatson Didn't you point out returning the implementation for jaeger remote sampler when I hadn't? :P But yeah I'd say the reason is that we're not able to reduce "publicness" at all by returning the interface - so may as well return the implementation which may provide some benefit in the future. For propagators, the probability of this is extremely low, but for other implementations like the remote sampler, I think it's reasonably possible and we may as well be consistent.

**Comment by bogdandrutu** [comment]
We should check for all these cases and fix them before 1.0 :)
