### ISSUE TITLE
Resource.DEFAULT no longer contains resources added via otel.resource.attributes property

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#2687]
**Describe the bug**
After loading the `otel.resource.attributes` property has been moved to the auto-configuration module, `Resource.DEFAULT` is set before this property is loaded and does not contain additional attributes defined by the user. While this is no problem for the `TracerProvider` (it gets its own copy, default merged with the property value) everything that calls `Resource.getDefault()` and expects it to have all possible resources will not work properly.

In v0.15.0 jaeger-thrift and zipkin call `Resource.getDefault().getAttributes().get(ResourceAttributes.SERVICE_NAME)` which will always return null (it's fixed on the main branch though).
`Resource.getDefault()` is still used in the opencensus shim, even on the main branch.

Aside from that, any `Resource.getDefault()` calls from the javaagent vendor distributions will also return an object with missing `otel.resource.attributes`.

Anyway, one way to fix that would be to just create a `ResourceProvider` SPI implementation inside the auto-configuration lib that loads the properties.

FYI @anuraaga 

**What version and what artifacts are you using?**
0.15.0

**Additional context**
https://github.com/signalfx/splunk-otel-java/pull/98#discussion_r568811754
https://github.com/signalfx/splunk-otel-java/pull/98#discussion_r568821406

**Comment by anuraaga** [comment]
If using autoconfigure, it should be picked up. If not, it should be possible to call `.setResource(...)` when configuring the SDK. So it seemed like this is ok and clear on programmatic vs environmental. Do you have a case you need the environment variable even though you configure the SDK programmatically?

**Comment by mateuszrzeszutek** [comment]
No, we use the auto-configuration module - and as I mentioned, it properly configures the tracer provider. The problem appears when you call `Resource.getDefault()` from some other place, totally unrelated to the tracer: `Resource.DEFAULT` does not contain the attributes from `otel.resource.attributes`.

**Comment by anuraaga** [comment]
Ah I see - so you mean if calling `Resource.getDefault()` outside of the span processors in a static way? Since span processors would have it provided by the tracer provider. I think we always expect Resource to be a part of the tracer provider, and not statically accessed - it's not in the API it's an implementation detail of the SDK right now. We've talked a bit about it potentially being useful in the API but that conversation is still ongoing.

Aside that, since the SDK doesn't handle environment variables, I wouldn't expect `getDefault` to handle them either, even with autoconfigure module present. I guess copying default resource into system properties is a work around to the above issue of exposing resource information to userspace - as such, would it be ok to extend the work around to parse the environment variable too? I think the general problem of exposing Resource to userspace is an interesting one, and I don't think we ever intended `Resource.getDefault()` to do so. We've heard of users who have different trace providers for different endpoints for whatever reason, something like multitenancy. In that case, it would be fragile for us to have system properties based on `Resource.getDefault()` exist that aren't part of the resource that happens to be used for a given codepath based on its tracer provider. Properly exposing it as `TracerProvider.getResource()` seems the least confusing but a huge change in the Resource-part-of-SDK model we have right now.

**Comment by jkwatson** [comment]
> In v0.15.0 jaeger-thrift and zipkin call Resource.getDefault().getAttributes().get(ResourceAttributes.SERVICE_NAME) which will always return null (it's fixed on the main branch though).

This is not true. It returns the default fallback service.name (which is `unknown_service:java`)

**Comment by jkwatson** [comment]
I think there could be a case for exposing the auto-configured Resource via a method in the auto-configuration module, but this isn't really in the spec at the moment.

We could probably make the env-var parsing resource code into an implementation of ResourceProvider, to make it consistent with the rest of the resource auto-detection code. Then, it would get loaded into DEFAULT if autoconfiguration were on the classpath.  What do you think of that idea, @anuraaga ?

**Comment by anuraaga** [comment]
Yeah on thinking more I think reconfiguring the default (moving that code to the SPI) should be fine even if it still has some issues when actually used in this way - doesn't add new issues :)

**Comment by jkwatson** [comment]
I'll PR this tomorrow
