### ISSUE TITLE
Unused method in ContextStorage

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2699]
https://github.com/open-telemetry/opentelemetry-java/blob/eb4c4b8721e2afbef808037ac3de777e5243fcca/api/context/src/main/java/io/opentelemetry/context/ContextStorage.java#L88

I think this should be removed until concrete use-case available

**Comment by anuraaga** [comment]
This was added for two users I think, one JFR, and is demonstrated in the JFR test. It follows my experience in Armeria too where the SPI just too tedious for some trivial use cases.

**Comment by bogdandrutu** [comment]
Do you have a real example of a usage of the Armeria API?

**Comment by anuraaga** [comment]
Here's the original Armeria issue and PR https://github.com/line/armeria/issues/2634 https://github.com/line/armeria/pull/2723

Unfortunately can't find any OSS usages. /cc @minwoox @ikhoon @trustin

**Comment by trustin** [comment]
As far as I know, LINE corporation uses that feature internally. @minwoox or @ikhoon could give some concrete example.

**Comment by bogdandrutu** [comment]
@anuraaga I see, but it seems to have very limited usage. Can we postpone adding it until a real user asks us to do it.

**Comment by anuraaga** [comment]
@bogdandrutu @sfriberg @HaloFour Users asked for it, that's why we added it

**Comment by HaloFour** [comment]
I am actively using this API now so that I can determine when the current span changes so that I can update MDC and have the span information included in the logs.

**Comment by minwoox** [comment]
Sorry for the late reply. 😅 
At LINE corporation, there's a service that uses Tomcat and Armeria together. (The service was originally built using Tomcat and add Armeria server with a different port.)

They used to have their own logic for request scoping using thread-local. So they can log MDC parameters and retrieve some instances they store in the thread-local.
It used to work well until they decided to use asynchronous client and server with the Tomcat together.
They couldn't do the request scoping for the requests that are served from the asynchronous server.

So we decide to add the sort of hook so that they could solve the problem. 😄

**Comment by bogdandrutu** [comment]
Ok.. too late then 👍
