### ISSUE TITLE
Hide StrictContextStorage implementation, expose only the flag to configure it

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java#2735]
If we do that we can remove the extra shaded dependencies from the Context package and the package becomes way smaller and simpler. I think this will be a huge win especially because we expect the Context package to be used the more.

Advantages like the number of classes we export (for platforms like Android) will be very appreciated by the users.

**Comment by anuraaga** [comment]
It's meant for use in real servers, such as in alpha deployments, too not just tests, so it was moved into here. Debugging context issues using real requests is important especially since users will have varying test coverage. 

Android is fine since it always goes through Proguard.

And we will need to use the weak map in trace package too once we add support for tracking leaked spans, not just scopes.

**Comment by bogdandrutu** [comment]
I think this is an overthinking on our side, and we will suffer because of this. Also right now there is a java property why does the class need to be public?

**Comment by bogdandrutu** [comment]
I am still suggesting to move it back to test until we really have some users asking for this. Premature optimization and overthinking will cause us a lot of pain to maintain all the APIs.

**Comment by bogdandrutu** [comment]
Last comment I promise :). Alternative we can have an extension with this, so at least if something breaks there or anything we can increase that version independently. Still believe `context` and `api` which will be distributed everywhere should be super slim and fewer APIs as possible

**Comment by anuraaga** [comment]
Context debugging is necessary to use context safely - it's not an extension but a required feature. I've even been paged late at night due to context bugs and it's a constant issue that comes up. Debug by flipping a flag, no need to rebuild the app - this is key.

It's not premature optimization but a feature lending from real experience with users that go async before having a proper async framework, which is most of them.

**Comment by jkwatson** [comment]
Yes. This was a concrete request from very experienced users. We need to keep this.

**Comment by bogdandrutu** [comment]
@jkwatson ok I understand that we need it. But in terms of having this as an extension instead of being in the main package? 

Also a bigger problem is the WeakHashMap class which probably we make a bigger mistake exposing as public and also making a promise to keep it as is. How is that related to context?

**Comment by jkwatson** [comment]
No more breaking changes at this point. We'll live with what we have.

**Comment by bogdandrutu** [comment]
Removing the WeakMap (hiding) should not be a breaking change based on the rules of internal package correct? I think you and @anuraaga told me that internal should not be consider part of the API but looks like it is in this case so this is not respecting the your own rule.

**Comment by bogdandrutu** [comment]
See https://github.com/open-telemetry/opentelemetry-java/blob/main/api/context/src/main/java/io/opentelemetry/context/internal/shaded/WeakConcurrentMap.java#L42

**Comment by anuraaga** [comment]
The comment about not making changes is outdated from before confirming our policy on expecting a bom. Now that we have the policy we can clean up that javadoc.

**Comment by bogdandrutu** [comment]
So we are allowed to make changes in that internal and evenimente removing it. That is great. Then if we are ok to hide the public StrictContextStorage and keep know the flag I think we can close this. I will make the change to do that in the PR if we agree with that.

@anuraaga indeed we have a comment to clarify the internal rules so that may be good to do 🙂

**Comment by bogdandrutu** [comment]
Decision was made with the majority of maintainers, no change required

**Comment by jkwatson** [comment]
I'd like to re-open this to make sure that we really need this class to be public. It's not clear that it's even useful as a public class right now, but only accessible via SPI/system property. 

@anuraaga If there's a reason this needs to be public, then I'll re-close, but otherwise, providing the functionality without the class would seem preferable.

**Comment by bogdandrutu** [comment]
@jkwatson I would add that the javadoc example should be updated. See https://github.com/open-telemetry/opentelemetry-java/issues/2762

**Comment by anuraaga** [comment]
I had to spend a day updating the agent to the new SDK for all the changes :P Will write docs about the internal package today. I'm inclined to not make any more changes to public API at all at this point.

**Comment by bogdandrutu** [comment]
But is this class somehow used directly? If yes, how?

**Comment by bogdandrutu** [comment]
Also no usage of this class in instrumentation https://github.com/open-telemetry/opentelemetry-java-instrumentation/search?q=StrictContextStorage&type=code
