### ISSUE TITLE
API: Multiple parent references

### ISSUE THREAD

**Issue by objectiser** [open-telemetry/opentelemetry-java#275]
Following on from the initial discussion about links vs references in #14, it appears that the current API supports links (to spans in other traces) but only a single parent span (reference).

OpenTracing does enable multiple parent references to be defined - which can be useful in identifying synchronization points (e.g. fork/join).

Will multiple parent references be supported? Both in the API and data model?

**Comment by yurishkuro** [comment]
@objectiser the multi-parent syntax in OpenTracing is actually rather vague because if you provide multiple references from different traces, the tracer has no way of knowing which trace the new span should belong to (it is left to a heuristic in the tracer). So I think having an explicit `setParent` is helpful.

The Links in OpenTelemetry are not restricted to be from the same or different traces, so the fork-join semantics are still supported.

**Comment by objectiser** [comment]
@yurishkuro That is not what the [current javadoc](https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/Link.java#L26) says, "A link to a {@link Span} from a different trace."

Even if this was changed to indicate it could be a link to spans in its own trace aswell, there would be an implied difference between the span that is provided as the parent, and those that are referenced via the `Link` - whereas in a join scenario all of the mentioned spans should have the same status.

**Comment by yurishkuro** [comment]
Javadoc is wrong, we discussed recently that there's no reason to limit links to different traces only.

> there would be an implied difference between the span that is provided as the parent, and those that are referenced via the Link - whereas in a join scenario all of the mentioned spans should have the same status.

Yes, but I think  it's a good thing, it makes it unambiguous in the general case from which span the child inherits its trace ID (instead of handling scenario where all links are from the same trace as a special case). Adding references as LINKs does not make those spans into "parents".

Also, fwiw, I have yet to see any real examples of using multiple references from the same trace. I think if we try to go through real examples that need that we'd need to talk in a lot more detail about _causality semantics_ of those references, because at the moment OpenTracing is exceptionally fast & loose about that. Specifically, the typical parent-child relationship between spans implies `parent.start happens-before child.start`, while saying little about the causality of span.end events. In contrast, the fork-join use cases typically quoted as an example of multi-parent spans implies `parent.end happens-before child.start` - a completely different causality than regular parent-child.

I would very much like to have a lot more clarity around the exact causality implications of different span relationships (related to #176), this has been one of the often criticized areas in the OpenTracing.

**Comment by bogdandrutu** [comment]
I am also curious why the Span that does not wait (join) for the child Spans (forks)?

Some pseudo-code here:
```java
Span parent = newSpan();
Span child1 = newSpan(parent, executeAsyncWork1);
Span child2 = newSpan(parent, executeAsyncWork2);
....
join(childThread1, childThread2);
```

Are you referring to the case where the async work is executed remotely (like cloud functions)? In that case where is the join point?

**Comment by objectiser** [comment]
Wasn't thinking specifically about a usecase, but the general pattern. Maybe as Yuri mentioned it just needs clarity about how certain patterns should be represented.

The immediate issue though was the `Link` description - which sounds like it needs updating.
