### ISSUE TITLE
Trace SDK has api dependency on experimental semconv artifact.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#2917]
See https://github.com/open-telemetry/opentelemetry-java/blob/v0.17.1/sdk/trace/build.gradle.kts#L14.

In my opinion an API dependency is not acceptable here if we really want to keep the ability to break semconv (which I think we should). Users will accidentally use this experimental package via the transitive dependency of the stable tracing SDK without being aware they are using experimental functionality.

This is more severe than but related to #2914.

**Comment by jkwatson** [comment]
Do we actually expose anything from the semantic conventions in our trace sdk APIs? If not, we can just change this to `implementation`, I think.

**Comment by Oberon00** [comment]
The question is what happens when the user uses an incompatible version of the semantic conventions. Is this prevented by the alpha BOM? I.e. does the alpha BOM include the stable BOM or does one need to declare versions of the stable and alpha BOM independently?

**Comment by jkwatson** [comment]
We do imply in our versioning doc that if you update your SDK, you might also have to update your *runtime* API dependency. This falls firmly into that camp. Our guarantee is that we won't break API users by updates in the SDK. If an API user is using an alpha dependency (like semconv), they should expect to have to update it from time to time, since we don't guarantee backwards compatibility of non-alpha artifacts.

We state this clearly:
```
Changes may be made that require changes to the an app's dependency declarations aside from just
incrementing the version on `MINOR` version updates. 
```

The alpha BOM doesn't not include the main BOM, but artifacts in the alpha bom certainly depend on artifacts in the stable bom, and vice versa.
