### ISSUE TITLE
Some semantic attribute constants are enums, other string constants

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java#3006]
In `SemanticAttributes`, there seem to be two types, `static final class` with constants and `enum`. I don't think I see a reason to have two types, can we consolidate?

**Comment by jkwatson** [comment]
This is currently controlled by the `allow_custom_values` attribute in the yaml conventions. So, if custom values are not allowed, we make it an `enum` so the user can't add custom values. Of course, that doesn't actually stop anyone from adding custom values, since anyone can create `AttributeKey` instances to their heart's content. But, it is a hint to the user that maybe they should use the provided list always in the one case, but can be more free-form in the other.

I'm not opposed to unifying, but I also don't see this as a major issue. Is it causing pain in some way at the moment, or just feels inconsistent?

**Comment by jkwatson** [comment]
> An alternative would be to define an interface the enums inherit from to allow them to be used with `setAttribute` without calling `.value()`. Does it seem reasonable? Otherwise I'd ditch the enums.

I'd love to see a proposal for this, yes. But, also, I'm fine with ditching with the enums, as they don't really provide much value, and do add confusion.

**Comment by anuraaga** [comment]
Realized I'll probably just ditch the enums. It's extremely tiny and inconsequential, but it feels weird that these two patterns would have some sort of difference in performance characteristics without otherwise being very useful as enums would.

**Comment by jkwatson** [comment]
Changing to not use enums sounds like the right way to go to me, as well.  👍

**Comment by harshita19244** [comment]
Could you assign me this issue, I would like to work on it
