### ISSUE TITLE
dependencyManagement gradle script creates unused dependencyVersions list

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3053]
dependencyManagement/build.gradle.kts exports a map of dependency -> version: https://github.com/open-telemetry/opentelemetry-java/blob/fd397bd78e46a5c3951c6f22e6b270f758bc662f/dependencyManagement/build.gradle.kts#L11-L12. However, this map is never used.

Furthermore, for dependencies passed in "simple dependency" format, it uses the group as map key instead of e.g. group + id. https://github.com/open-telemetry/opentelemetry-java/blob/fd397bd78e46a5c3951c6f22e6b270f758bc662f/dependencyManagement/build.gradle.kts#L120

**Comment by anuraaga** [comment]
The map is used in only a couple of places like here

https://github.com/open-telemetry/opentelemetry-java/blob/main/build.gradle.kts#L348

Using only group is intentional to model the version of the "aligned artifacts" - this is mainly so consumers of `versions` don't have to care whether it's `grpc-bom`, `grpc-stub`, etc that we are actually using for dependency management. It could create corner cases indeed and adding the artifact name would be fine too, I thought it made things simpler though.

**Comment by Oberon00** [comment]
Ah, I did not see the map was used! It seems I misunderstood the concept of an artifact group then. Should all the versions inside a group usually be aligned? I.e. does a group usually refer to a single project that is just split into multiple artifacts?

**Comment by anuraaga** [comment]
@Oberon00 I think it's both common for artifacts in a group to be aligned, and common for them to not be aligned :) For our purpose the former was enough so went with it.

**Comment by jkwatson** [comment]
@Oberon00 do we need to keep this issue open?

**Comment by Oberon00** [comment]
Sorry, this issue was invalid.
