### ISSUE TITLE
Tracer implementing Closable

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#32]
In OT, `Tracer` implements `Closable`, which lets users flush pending `Span`s and dispose related resources.

Is there any point against this for the new API? I don't see any, but let me know ;)

**Comment by SergeyKanzhelev** [comment]
https://github.com/census-instrumentation/opencensus-java/issues/646

**Comment by tedsuo** [comment]
In OT, It was helpful to close the tracer without knowing the underlying implementation.

@bogdandrutu please add `Closable` unless you object.

**Comment by bogdandrutu** [comment]
I think close is not good because the Tracer is shared between multiple threads and race conditions can happen (users need to synchronize the close call, or make sure they close after all the usages of the Tracer). I probably suggest having a "Flush" method if that is needed for tests or for the shutdown hook. Also a good question is if the Flush should be a method on the Tracer implementation or on the main Tracer interface.

**Comment by carlosalberto** [comment]
A flush method is ok - essentially we need a way to let remaining `Span` instances be sent in case the service is about to shutdown.

**Comment by tedsuo** [comment]
We need to gather use cases to better understand if `Close` and/or `Flush` should be on the `Tracer` interface.

Main use case:
* Shutdown code

**Comment by bogdandrutu** [comment]
We do have a shutdown method on the SDK. I think the shutdown belongs to the implementation that is used.
