### ISSUE TITLE
Add support for the http/protobuf export for OTLP

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#3395]
Recent spec changes have suggested that SDKs SHOULD support http/protobuf as well as grpc for OTLP exporters.

**Comment by jack-berg** [comment]
Two clarifying questions:

1. There's currently an `OtlpGrpcSpanExporter`. One strategy would be to change this to an all-in-one `OtlpSpanExporter` which supports all the protocols. My preference would be to add a separate `OtlpHttpSpanExporter` which handles both the `http/protobuf` and `http/json` based on configuration. Thoughts?
2.  The gRPC exporters support the ability to substitute out the transport implementation (netty or ok http). For HTTP we could choose a single HTTP client (Apache HttpClient and Ok HTTP seem like good candidates), or we could make it configurable by providing some request builder interface that users can implement with the HTTP client of their choice (with prebuilt implementations for certain HTTP clients).

**Comment by jkwatson** [comment]
Great questions. 

1. I think we should keep them separate, especially because of considerations for 2.
2. I think we choose okhttp3 and shade it in. Although, it might be worth seeing if it works with good ol' HttpUrlConnection, only because on java 11+ I believe it is implemented under the hood with the new java HttpClient, which would definitely be the way to go if we could enforce java 11+.

These are just my current opinions, not strongly held.

**Comment by anuraaga** [comment]
Agree that we should go ahead and use okhttp, and have a separate artifact for the HTTP exporters compared to the default gRPC ones. HttpUrlConnection even when implemented with the java 11 client doesn't support HTTP/2 I believe so would be a pretty big performance gap vs okhttp.

I wasn't planning on shading it since we don't shade gRPC. We could probably decide that later.

@jack-berg Are you volunteering to implement this? :-) If so will assign the issue

**Comment by jack-berg** [comment]
@anuraaga Sure - I'll give it a go!
