### ISSUE TITLE
autoconfigure indirectly uses Thread.currentThread().getContextClassLoader()

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#3634]
This has cost me some time debugging: I used OTel inside Google Cloud Functions https://cloud.google.com/functions/docs/first-java and added `opentelemetry-sdk-extension-resources` to the classpath. In unit tests, everything worked but not when actually executing the test with the `com.google.cloud.functions.invoker.runner.Invoker`. The reason turned out to be that that one uses a custom context class loader. I assume Java Web Servers might be affected by this too.

I was able to work around this using

```java
final ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
Thread.currentThread().setContextClassLoader(getClass().getClassLoader());
try {
  this.otelSdk = OpenTelemetrySdkAutoConfiguration.initialize();
} finally {
  Thread.currentThread().setContextClassLoader(contextClassLoader);
}
```

The fix / behaviour change in autoconfigure would be to use the [`ServiceLoader.load` overload taking a Loader](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html#load-java.lang.Class-java.lang.ClassLoader-) and passing the classloader of the autoconfigure class.

I'm not completely sure if this is a bug (at all or in otel-java), but I am sympathetic to the opinion that relying on the context class loader is an anti-pattern, without having enough background knowledge to be sure about it.

**Comment by jkwatson** [comment]
seems like an easy change to make, and I can't see the harm. @anuraaga has more experience than I do in this area, though.

**Comment by anuraaga** [comment]
Thanks - agree that it is idiomatic to always provide an API that accepts a ClassLoader when doing service loading.

**Comment by Oberon00** [comment]
> Thanks - agree that it is idiomatic to always provide an API that accepts a ClassLoader when doing service loading.

I wonder if we actually want to provide a classloader as parameter. Wouldn't it be enough to just always use the same classloader in which the autoconfigure artifact is loaded? At least that feels like a better default to me than the context classloader.

**Comment by trask** [comment]
I think it's more conventional for the context class loader to be the default, because this allows the class that's doing the loading (e.g. Spring or OTel) to be shared (e.g. in an ear file or shared app server library), and still see and load implementations of its interfaces that are in your app (e.g. in a war file).

I'm surprised that Google Cloud Functions isn't setting the context class loader for you to something that can see all of your classes? tho a quick google pulls up this, which seems to say that they are(?) https://github.com/GoogleCloudPlatform/functions-framework-java/commit/a3d23cc12df52cb10ee0102e50cd54eb943527e6

**Comment by cyrille-leclerc** [comment]
Capability to specify the class loader when using auto configuration would be great for the Otel Maven extension. I couldn't use the auto configuration resource provider and workarounded using the OTEL_RESOURCE_ATTRIBUTES variable because of class loader issues as commented on https://github.com/open-telemetry/opentelemetry-java-contrib/pull/112/files#diff-8625ba4b8e68496923fa886962656dc739e75194535a5d9a9c7a81e555fff294R100

**Comment by obailiumingo** [comment]
hello, according to my testing. som third-package, like kafka, s3, had flexible strategy to load class during configuration.

in the newest fix. it only work well when config it in the *service* method. when I want to do these in the constructor, it get the error "no class found"。
