### ISSUE TITLE
Metrics Views API: Wildcard Support

### ISSUE THREAD

**Issue by hdost** [open-telemetry/opentelemetry-java#3642]
Mimic dotnet Tracer
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/TracerProviderSdk.cs#L161

Related
https://github.com/open-telemetry/opentelemetry-dotnet/issues/2377

**Comment by hdost** [comment]
So I believe it already is part of the specification here https://github.com/open-telemetry/opentelemetry-specification/blob/02a1679c22f71ba35b925c7995544e88290e5133/specification/metrics/sdk.md#view when it refers to registering views. Being able to provide a wildcard on the name so that many exports can happen.

**Comment by jkwatson** [comment]
Can you update the title of this issue to make it clear that it's related to the Views API in the SDK?

**Comment by jsuereth** [comment]
@hdost Quick question on this.  Right now, you can pass any `Predicate<String>` to the SDK API, with direct regex support.

AFAIK this meets the spirit of the spec, because you have complete regex matching.  Can you be more specific with your request?  Do you want a specific way to convert from `glob String` => `Predicate<String>`?

**Comment by hdost** [comment]
I apologize, this was a misunderstanding on my part. So long as it fits that use case I see no reason to keep this open.
