### ISSUE TITLE
Add an OTLP http/json exporter

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#3651]
Based on https://github.com/open-telemetry/opentelemetry-specification/issues/1957 we would like to add prototypes in other languages to validate this.

Lightstep has interest in this, so if everybody has interest in this (or has his/her own prototype) please speak up ;)

**Comment by tnevolin** [comment]
Here I am.

**Comment by jkwatson** [comment]
@anuraaga and I had decided that we don't particular think this is of high value when we already have OTLP/grpc *and* OTLP/http. What is the benefit of having yet another http-based exporter?

**Comment by carlosalberto** [comment]
Overall we need prototypes in other languages - @jkwatson do you think then this would be a _bad_ idea to add it, even if Lightstep were to contribute it fully?

**Comment by jkwatson** [comment]
> Overall we need prototypes in other languages - @jkwatson do you think then this would be a _bad_ idea to add it, even if Lightstep were to contribute it fully?

more code to maintain. Could it be built in opentelemetry-java-contrib for the prototype?

**Comment by anuraaga** [comment]
I think it actually is a bad idea to be honest, even in the contrib repo. It's yet another option users need to choose from - while grpc and http do have clear tradeoffs and use cases (http2 vs 1, large binary vs small, etc), json doesn't - it's actually worse in basically every way I think, less performance, larger binary size due to inclusion of jackson. I think there's only potential for user confusion with no benefit if we add the JSON export.

I understand the desire for a prototype but it still should be something people actually use I guess to be a valid prototype.

Shouldn't one prototype in JS (I think the main use case) be enough given it'll either work or not work?

**Comment by anuraaga** [comment]
So we do use json for the logging OTLP exporter - perhaps that can be used in some way for this. If collector had a receiver that accepted log lines of ResourceSpans json that would be useful!

**Comment by carlosalberto** [comment]
@anuraaga In JS it already exists, but the point is that we need to test in other languages (if the time is needed). Having it in a single language is not much of help. 

> So we do use json for the logging OTLP exporter - perhaps that can be used in some way for this.

That sounds like a _hack_ and I wouldn't go for it.

As the name implies, it's only a prototype - we may even leave it as as something like EXPERIMENTAL, and retire it or something (once we validated a few things, so we know that if we ever need this in any language other than JS, we are good to go). Also, being in the contrib repo means you don't have to maintain it. 

Let me know ;)

**Comment by anuraaga** [comment]
> That sounds like a hack and I wouldn't go for it

An http/json exporter seems like more of a hack really - the log exporter is actually useful.

> we may even leave it as as something like EXPERIMENTAL, and retire it or something

That sounds like it doesn't need to even be merged or could live in a fork right? I don't want users to find this.

**Comment by anuraaga** [comment]
FWIW we've gone through a lot of effort making the proto exporter very efficient with no binary size or similar tradeoff at all. Languages that haven't done this would probably be more receptive to trying a json approach, we just don't really have any use case for it.

**Comment by carlosalberto** [comment]
> An http/json exporter seems like more of a hack really

Go tell that to the JS group ;)

But jokes aside, as I said, there's no actual use of it right now in Java, other than verifying the encoding and the rest will not be a problem in the future for other languages (better be safe than sorry). So yes, let's keep it in another repo, open a Draft PR, keep it there for discussing, and that would be all.

**Comment by anuraaga** [comment]
I have a feeling they'd mostly agree :)

Draft PR or similar seems good. It should be pretty small, we already have the marshaling

https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/test/java/io/opentelemetry/exporter/otlp/internal/traces/TraceRequestMarshalerTest.java#L364

Since we don't have to worry about making it publishable it might just be two lines of change in this file

https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/otlp/common/src/main/java/io/opentelemetry/exporter/otlp/internal/ProtoRequestBody.java#L44

**Comment by tnevolin** [comment]
@anuraaga 
You mentioned existing code in main SDK repository. Do you want modification and draft PR to be done against this repository or move exporter completely to contrib one and make draft PR from there?

**Comment by jkwatson** [comment]
Draft PR here is fine for spec review...we won't plan on actually merging it.

**Comment by jack-berg** [comment]
This has been added for testing purposes in #4435.
