### ISSUE TITLE
Make semconv packages explicitly versioned

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-java#3764]
**Is your feature request related to a problem? Please describe.**
OpenTelemetry semantic convention are considered to be a living standard to which changes are allowed over time.
As the conventions change over time, every version of the Otel specification captures/freezes a version of semantic
conventions. The telemetry sources are expected to explicitly declare the version of the semantic conventions
they use by recording the corresponding Schema URL in the emitted telemetry.

This repo currently declares a single semconv package. When the semantic conventions change in the specification
we will be forced to change the semconv package, which may break users of semconv package (e.g. if a name of an
attribute is change it will break the importing code, it won't compile any more).

**Describe the solution you'd like**
We iterated on this problem in Go SDK and the solution we came up with is to have one semconv package per version
of semantic conventions, see [the PR](https://github.com/open-telemetry/opentelemetry-go/pull/1987) and [current structure](https://github.com/open-telemetry/opentelemetry-go/tree/main/semconv).

I suggest that we implement the same approach here, in this repo.

**Describe alternatives you've considered**
One alternate is to keep current design, but it doesn't match the intent of telemetry schemas and how they allow
semantic conventions to evolve.

**Additional context**
See [OTEP0152]( https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md) for the motivation of schemas and how the changes are allowed.

**Comment by tigrannajaryan** [comment]
>One thing that we're considering is to move the semconv module out of this repository altogether, and publish it like we do the proto bindings now.

This is also a good approach.

> as the java module system does not allow exporting the same package from more than one `jar` artifact in the same classloader.

What if the version number is explicitly part of the package name? In that case it will be allowed, right?

We do want multiple semconv packages to be importable by one application. The use case is when you use multiple instrumentation libraries and they happen to depend on different versions of semconv. This is an explicitly allowed situation by OTEP.

**Comment by anuraaga** [comment]
I think one big issue we have right now is semantic conventions usually don't change in spec versions. Sometimes they do though. We don't want to version semantic attributes with respect to the spec version since it means many versions with no breaking changes. Ideally semantic attributes were versioned separately from the spec, using actual semver to understand the changes. It means any attribute name change in semantic conventions bumps it's major version, possibly causing us to be at v2 or v3 of semantic attributes while the spec is at 1.8 or 1.9.

Is semver of semantic attributes achievable?

**Comment by anuraaga** [comment]
> A possible alternate approach is to only create new packages when there are any changes in the semantic conventions.

This is currently the approach I'm most in favor of, I think it causes the least confusion for actual users of the conventions in instrumentation without having many duplicate packages. Without any corresponding version in the spec, we could just bump the package version in our repo when we find a breaking change. Wouldn't real semver provide the least confusion, both for SDKs and backends so they know when something needs to be updated in a hard way? I don't think end users care about the version of the spec at all, they just use versioned instrumentation libraries or backends that provide features, the version of the spec / semantic attributes is basically abstracted away.

**Comment by anuraaga** [comment]
semver here means incrementing the major version when there is a breaking change as usual - this has become the popular way of versioning things since it tends to be important to know when there's a breaking change ;) I have a feeling this point was lost in the OTEP.

I don't think the package versions in Java have to match a version in the spec, so if the spec does not decide to change semantic attributes to semver, it should be OK. I don't think we'll be publishing a new package and/or artifact every version bump though even when there aren't any breaking changes since while not ideal conceptually, it seems better than https://github.com/open-telemetry/opentelemetry-java/issues/3764#issuecomment-946106545

**Comment by jack-berg** [comment]
Resolved by #5786.
