### ISSUE TITLE
Comment about no-op formatter is misleading

### ISSUE THREAD

**Issue by SergeyKanzhelev** [open-telemetry/opentelemetry-java#378]
This comment is misleading:

https://github.com/open-telemetry/opentelemetry-java/blob/60013e3de6092d906bf19ddd72452337d08c4a7a/api/src/main/java/io/opentelemetry/trace/Tracer.java#L185-L188

Perhaps do not say no-op, say default at least

**Comment by SergeyKanzhelev** [comment]
Same for Text formatter

**Comment by arminru** [comment]
Should this comment be read as "If no implementation *of OpenTelemetry* is provided then the default implementation *of [Binary|HttpText]Format* is used."? I.e., if the user is using the blank API without any tracing vendor configured, they get whatever `DefaultTracer` provides?

In that case, for binary it would (currently) indeed be a no-op impl (`DefaultTracer.NoopBinaryFormat`) and for `HttpTextFormat` `DefaultTracer` returns `TraceContextFormat`.

Both defaults should be defined in the API in my opinion since they might affect the application's behavior and should be something to rely on. We could clearly document that API users can rely on proper TC propagation if no OT implementation is configured - or would you rather avoid such guarantees?
Once [W3C TraceContext Binary Protocol](https://w3c.github.io/trace-context-binary/) is final, the default for `BinaryFormat` would likely be switched from no-op to that one, right?

**Comment by carlosalberto** [comment]
I think we should state clearly that this **will be** the W3C Context, instead of "usually" (remember this is when **no tracer** was provided).

I think we can mention the Binary protocol at this moment, even if it's not marked as final. Right, @SergeyKanzhelev ?

**Comment by SergeyKanzhelev** [comment]
@carlosalberto makes sense. It will be clearer if we call it what it is.

**Comment by carlosalberto** [comment]
Closing it for now. Feel free to reopen otherwise @SergeyKanzhelev ;)
