### ISSUE TITLE
[Metrics SDK] async instruments should only collect values once, even if they product multiple metric streams via multiple views

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java#3856]
Today if you register multiple views against an async instrument, it will invoke the callback for their values twice during the same collection cycle.   This should happen only once-per-collection cycle

**Comment by jack-berg** [comment]
Currently this isn't possible. Instead of invoking the callback twice, it generates a configuration error with a confusing error message. 

For example this code:
```
    InMemoryMetricReader cumulativeReader = InMemoryMetricReader.create();
    SdkMeterProvider sdkMeterProvider =
        SdkMeterProvider.builder()
            .registerMetricReader(cumulativeReader)
            .setMinimumCollectionInterval(Duration.ofSeconds(0))
            .registerView(InstrumentSelector.builder().setInstrumentType(InstrumentType.OBSERVABLE_COUNTER).build(),
                View.builder().setAggregation(Aggregation.lastValue()).build())
            .registerView(InstrumentSelector.builder().setInstrumentType(InstrumentType.OBSERVABLE_COUNTER).build(),
                View.builder().setAggregation(Aggregation.sum()).build())
            .build();
    Meter meter = sdkMeterProvider.get(CardinalityTest.class.getName());

    AtomicLong counter = new AtomicLong();
    meter.counterBuilder("foo")
        .buildWithCallback(measurement -> measurement.record(10, Attributes.builder().put("count", counter.incrementAndGet()).build()));

    for (int i = 0; i < 2; i++) {
      cumulativeReader.collectAllMetrics().forEach(System.out::println);
    }
```
Produces the following warning:
```
WARN io.opentelemetry.sdk.metrics.internal.state.MeterSharedState - Found duplicate metric definition: foo
	at unknown source
		To enable better debugging, run your JVM with -Dotel.experimental.sdk.metrics.debug=true
Causes
- InstrumentType [OBSERVABLE_COUNTER] is async and already registered
Original instrument registered with same name but is incompatible.
	at unknown source
		To enable better debugging, run your JVM with -Dotel.experimental.sdk.metrics.debug=true
```
The SDK still initializes and exports the data as a gauge, since that was the first view registered.

This behavior isn't correct since you want to be able to configure multiple views for the same instrument. If I run that same snippet on the prototype that allows [multiple callbacks](https://github.com/open-telemetry/opentelemetry-java/pull/4143), then I get no error message logged, but the export behavior is the same (i.e. it only exports as a gauge and the second sum view is ignored).

I think we should re-write this issue to say that async instruments should be able to produce multiple metric streams view views, and their callbacks should only be invoked once when multiple views are registered.
