### ISSUE TITLE
EmptyMetricData throws exception when `getType()` is called, breaking unit test assertion paths.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java#3956]
This is mostly an annoyance for unit test assertions using the `has` functionality that relies on getType, but is also possible in user-provided exporters.

If we plan to throw on `getType` for EmptyMetricData, we should probbaly deprecate the method or make it private.

E.g. when trying to write a test that hits cardinality limits, I'm seeing empty-metrics get reported.  It could be this is cleaned up before hitting exporters.  Either way, it's a bit odd to deal with, e.g.
```
TemporalMetricStorageTest > synchronousCumulative_dropsStaleAtLimit() FAILED
    java.lang.UnsupportedOperationException: EmptyMetricData does not support getType().
        at io.opentelemetry.sdk.metrics.internal.aggregator.EmptyMetricData.getType(EmptyMetricData.java:63)
        at io.opentelemetry.sdk.testing.assertj.metrics.MetricDataAssert.hasDoubleSum(MetricDataAssert.java:155)
```

**Comment by jack-berg** [comment]
It shouldn't be possible for `EmptyMetricData` to escape the SDK today, since [MeterSharedState](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MeterSharedState.java#L68) checks `MetricData#isEmpty()` before adding to the result list. 

None of the current values of `MetricDataType` are accurate for `EmptyMetricData`, so we'd have to: 1. Add another value to `MetricDataType`, 2. Make `MetricData#getType()` nullable. 

But thinking more about `MetricData` and its `#getType()` method, if the goal is to make `MetricData` implementable by users so that they can provide custom aggregators, does this method even make sense? We might consider removing `#getType()` in favor of something like:
```
// Extend MetricData to have an associated type which extends PointData
public interface MetricData<T extends PointData> {
  ...
  // Replace #getType() with #getDataType(), which returns the class of the PointData associated with the MetricData
  Class<T> getDataType();
  // Change response of #getData from Data<?> to Data<T>
  Data<T> getData();
```

**Comment by jack-berg** [comment]
Closing because it should be impossible for `EmptyMetricData` to escape the SDK and make it to `MetricExporter`. If it does make it to `MetricExporter` its a bug. 

Revisiting my comment questioning whether `MetricDataType getType()` is appropriate to have at all: the answer is yes. The `MetricData` interface is a reflection of the metrics data model. The addition of custom aggregators in the future won't change the data model.
