### ISSUE TITLE
A way to get  intance of SpanExporter

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java#3963]
I want to custom my own SpanProcessor. But it is difficult to build or get a SpanExporter. Because it has too many propertis to set. Then the SpanExporterConfiguration /OtlpConfigUtil's methods and class are not public. I have to copy the code to my own project. 

Can you set them public or a way to get the intance of SpanExporter?

**Comment by chenjazz** [comment]
I find `AutoConfigurationCustomizerProvider` ,but it can not custom the SpanProcessor.

**Comment by jack-berg** [comment]
We could extend `AutoConfigurationCustomizer` with a method like:
```
AutoConfigurationCustomizer addSpanProcessorCustomizer(
      BiFunction<? super SpanProcessor, ConfigProperties, ? extends SpanProcessor> spanProcessorCustomizer);
```
What type of functionality are you looking to implement in the `SpanProcessor`?

**Comment by chenjazz** [comment]
Thank you @jack-berg .
It's useful to add `AutoConfigurationCustomizer#addSpanProcessorCustomizer` . 
But I want to use `SpanProcessor#onEnd` method,so I can sample according to span's some arrtibutes,like this:
Before code:
```java
  @Override
  public void onEnd(ReadableSpan span) {
    if (span == null || !span.getSpanContext().isSampled()) {
      return;
    }
    worker.addSpan(span);
  }
```
After code:
```java
  @Override
  public void onEnd(ReadableSpan span) {
    if (span == null) {
      return;
    }
   //It is must be sampled when error.
    if (span.toSpanData().getStatus().getStatusCode().equals(StatusCode.ERROR)){
      worker.addSpan(span);
      return;
    }
    if (!span.getSpanContext().isSampled()) {
      return;
    }
    worker.addSpan(span);
  }
```
How can I use sdk to  complete this?

**Comment by anuraaga** [comment]
Hi @chenjazz - we'd generally expect a decorating exporter for that instead of span processor. You can use `addSpanExporterCustomizer` to wrap the defaults with an exporter that contains logic that filters out exported spans. Does that work for you?

**Comment by chenjazz** [comment]
@anuraaga But before `SpanExporter` expot the span ,the SpanProcessor filter it already like above code,
 I use `TraceIdRatioBasedSampler`, when the span `isSampled == false`,but span's status is Error. I also want to sample it.
So `addSpanExporterCustomizer` is not useful.

**Comment by chenjazz** [comment]
Span start (TraceIdRatioBasedSampler:isSampled == false) 
--->user's code (Error : I also want to sample it when error)
--->SpanProcessor (Filter span when isSampled == false )
--->SpanExporter (can not get span)

**Comment by anuraaga** [comment]
@chenjazz Ah I see - an unsampled span has no data recorded so there isn't anything to export really. So even if that check was skipped, the exporter wouldn't work correctly I think - you would need to change your sampler to `Sampler.alwaysOn` if you want to be able to delay the export decision like that.

**Comment by chenjazz** [comment]
`Sampler.alwaysOn` is not useful. My requirement hava 2:
1.Use TraceIdRatioBasedSampler
2.Sampled when error

If sampled decision in span start,it is difficult to do above.
@anuraaga

**Comment by anuraaga** [comment]
@chenjazz Unfortunately using TraceIdRatioBasedSampler but "recovering" spans that were not sampled in the processor isn't supported in OTel's SDK model. An unsampled span records no data and cannot be exported - even if you were able to have a processor with that described logic, `if (span.toSpanData().getStatus().getStatusCode().equals(StatusCode.ERROR)){` would always be false for unsampled spans since we don't record data, such as status for it.

It seems that you are trying to combine two types of sampling, head sampling by probability and tail sampling by error status. This configuration is not supported - if wanting to filter spans by status, you would need to stop using the TraceIdRatioBasedSampler to sample at the head, you could do a probabilistic filtering in the exporter if you wanted to. You may have issues with partial traces though if not careful with such an approach as spans will still get propagated even when not exported.

**Comment by chenjazz** [comment]
@anuraaga Thank you.

**Comment by chenjazz** [comment]
Will you add `AutoConfigurationCustomizer#addSpanProcessorCustomizer`  in next version? @jack-berg

**Comment by anuraaga** [comment]
@chenjazz I don't think we're currently planning on adding that since we still haven't found a use case. For example, in the snippet you want to achieve `if (span.toSpanData().getStatus().getStatusCode().equals(StatusCode.ERROR))` won't work due to the way the SDK records data anyways.

To achieve tail sampling based on status code, I think you will need change the Sampler to always_on. In that case, decorating the SpanExporter will work fine for filtering, though you may also want to look into the OpenTelemetry Collector's support for tail sampling

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor
