### ISSUE TITLE
OpenTelemetry interface add methods to get log emitter provider

### ISSUE THREAD

**Issue by wallezhang** [open-telemetry/opentelemetry-java#4081]
**Is your feature request related to a problem? Please describe.**
After the SDK is auto configured by `AutoConfiguredOpenTelemetrySdk` class, I can't get the auto configured log emitter provider or log emitter, because of the `globalOpenTelemetry` field is wrapped by `ObfuscatedOpenTelemetry` class which implement `OpenTelemetry` interface, and the interface has no declare methods to get log emitter provider.

**Describe the solution you'd like**
Add some methods to `OpenTelemetry` interface to get log emitter provider or log emitter.

**Describe alternatives you've considered**

**Additional context**

**Comment by wallezhang** [comment]
If the solution is work, I can submit a PR to this feature.

**Comment by jack-berg** [comment]
If you have an instance of `AutoConfiguredOpenTelemetrySdk`, you can access an instance of `SdkLogEmitterProvider` as follows:

```
SdkLogEmitterProvider sdkLogEmitterProvider = autoConfiguredOpenTelemetrySdk
        .getOpenTelemetrySdk()
        .getSdkLogEmitterProvider();
```

`OpenTelemetry` is part of the API, and there are no current plans to have a log API, or expose the log SDK in the API.

**Comment by wallezhang** [comment]
I think the only way to get an instance of `AutoConfiguredOpenTelemetrySdk` is to invoke `io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk#initialize` method. If I call `io.opentelemetry.api.GlobalOpenTelemetry#get` method directly, I can't get this instance. Or if I develop an instrumentation module, I can't get the instance either. Because the process of automatic configuration is completed in the `io.opentelemetry.javaagent.tooling.AgentInstaller#installBytebuddyAgent` static method.

**Comment by wallezhang** [comment]
Maybe we can add a static field to `AutoConfiguredOpenTelemetrySdk` class to hold the instance?

**Comment by anuraaga** [comment]
Hi @wallezhang - it is intentional to not provide access to the logs emitter when using the agent and it is not intended for use in instrumentation. OpenTelemetry is not creating a logging API as there are already many out there, instead the approach is to bridge existing logging frameworks into OpenTelemetry by creating appenders for example. Any code should continue to use something like java.util.logging or SLF4J. 

Some discussion on this has happened on the opentelemetry-specification repo

https://github.com/open-telemetry/opentelemetry-specification/issues/2234

If you have a use case for a logging API that you believe hasn't been covered in that discussion you should probably file an issue in the spec repo to see what others think about it. But presumably SLF4J should work fine for your use case.

**Comment by wallezhang** [comment]
Thanks for reply. I want to export the log manually by SDK, so I will create a custom appender, and export log by auto configured log emitter provider. And I found `Logback` instrumentation in java agent project, also get the log emitter provider through a global holder like this:

```java
public void capture(ILoggingEvent event) {
    LogBuilder builder =
        GlobalLogEmitterProvider.get()
            .logEmitterBuilder(event.getLoggerName())
            .build()
            .logBuilder();
    mapLoggingEvent(builder, event);
    builder.emit();
}
```

So it seems that the only way is to save the instance of `AutoConfiguredOpenTelemetrySdk` somewhere?

**Comment by anuraaga** [comment]
If you'd like to initialize and use the SDK directly to emit logs, it will work, but the SDK managed by the javaagent won't be made accessible for app code because it is not meant to be used directly, hence there not being a logs API in OpenTelemetry. You should really be using SLF4J or similar, what's your use case for exporting logs via the OpenTelemetry SDK?

**Comment by wallezhang** [comment]
Yes, don't consider getting the SDK managed by javaagent for the time, because the log appender has been provided in Java agent project. And for my use case, I just depend on OpenTelemetry Java SDK, and I need to customize a log appender which will export logs to OpenTelemetry collector.

All the features that I want to do have already been implemented in the `opentelemetry-java-instrumentation` project, but I can't depend on Java agent, so I need to implement them manually. The feature is similar to the following:

```java
public class OpenTelemetryAppender extends AppenderBase<ILoggingEvent> {

  public OpenTelemetryAppender() {}

  @Override
  protected void append(ILoggingEvent event) {
    capture(event);
  }

  public void capture(ILoggingEvent event) {
    LogBuilder builder =
        GlobalLogEmitterProvider.get()
            .logEmitterBuilder(event.getLoggerName())
            .build()
            .logBuilder();
    mapLoggingEvent(builder, event);
    builder.emit();
  }

}
```

**Comment by anuraaga** [comment]
Ah are you just trying to emit logback logs with OpenTelemetry without the javaagent? (You mentioned Logback in a previous comment).

The logback instrumentation in `opentelemetry-java-instrumentation` does not require the java agent. We call this library instrumentation.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library

If there are features missing from that which you need, we may be able to add them so please let us know - we are hoping users use our provided libraries rather than having to map events in their own codebases. That is why we basically don't expect users to directly use the logs SDK.

**Comment by wallezhang** [comment]
Yeah, but how do I use the library? I can't find the dependency in maven central repository. And the library also use a `GlobalLogEmitterProvider` class to hold the `LogEmitterProvider`. So should I initialize a instance of `LogEmitterProvider ` manually and invoke `io.opentelemetry.instrumentation.api.appender.GlobalLogEmitterProvider#set` method to set the global instance?

**Comment by anuraaga** [comment]
Ah sorry - that will be released in 1.10.0 which is happening today and will be on Maven Central then. The README seems to be up to date, you use `OpenTelemetryAppender.setSdkLogEmitterProvider` to register the log emitter provider. Does that work for you?

**Comment by wallezhang** [comment]
Yes, it works for me. And I have another question, why log emitter doesn't support sampler? Maybe I should open a new issue to discuss it?

**Comment by wallezhang** [comment]
It's already has a issue about this, open-telemetry/opentelemetry-specification#2237

**Comment by jack-berg** [comment]
@wallezhang were you able to resolve your issue with the information provided in the corresponding [spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2332#issuecomment-1044356703)?

**Comment by wallezhang** [comment]
> @wallezhang were you able to resolve your issue with the information provided in the corresponding [spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2332#issuecomment-1044356703)?

Yes, I have resolved my issue. The auto configured `LogEmitterProvider` will be injected to the appender automatically by java agent.
