### ISSUE TITLE
Add SdkLogEmitterProviderConfigurer and ConfigurableLogExporterProvider

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4095]
Similar to SdkTracerProviderConfigurer/SdkMeterProviderConfigurer and ConfigurableSpanExporterProvider/ConfigurableMetricExporterProvider.

(currently there's no way to add a custom log exporter when using the autoconfigure module)

**Comment by jack-berg** [comment]
I think we ought to extend the `AutoConfigurationCustomizer` to add customizers for `SdkMeterProviderBulder` and `SdkLogEmitterProviderBuilder`. 

However, we should think through whether now is the right time to extend that interface, since `AutoConfigurationCustomizer` lives in the stable `:sdk-extensions:autoconfigure-spi` module, but neither the log sdk or the metrics sdk is stable yet. 

I think its probably safe to add these customizers considering that `OpenTelemetrySdk` in `:sdk:all` is stable an also has methods that accept / return `SdkMeterProvider` and `SdkLotEmitterProvider`.

**Comment by wallezhang** [comment]
@jack-berg I found the `SdkMeterProviderConfigurer` and `ConfigurableMetricExporterProvider` is in the `:sdk-extensions:autoconfigure` module, maybe we can create the `SdkLogEmitterProviderConfigurer` and others in the same module

**Comment by jack-berg** [comment]
@wallezhang `AutoConfigurationCustomizer` represents the newer pattern we want to emulate in logs and metrics. It replaces some of the functionality of existing SPIs, such as `SdkTracerProviderConfigurer`.

[#4127](https://github.com/open-telemetry/opentelemetry-java/pull/4127) illustrates how I think we should extend it for metrics. Once that PR lands, I plan on extending it similarly for longs. 

The result would be that `AutoConfigurationCustomizer` would have the following new methods:
```
  AutoConfigurationCustomizer addMeterProviderCustomizer(BiFunction<SdkMeterProviderBuilder, ConfigProperties, SdkMeterProviderBuilder> meterProviderCustomizer);
  
  AutoConfigurationCustomizer addMetricExporterCustomizer(BiFunction<? super MetricExporter, ConfigProperties, ? extends MetricExporter> exporterCustomizer);
  
  AutoConfigurationCustomizer addLogEmitterProviderCustomizer(BiFunction<SdkLogEmitterProviderBuilder, ConfigProperties, SdkLogEmitterProviderBuilder> logEmitterProviderCustomizer);
  
  AutoConfigurationCustomizer addLogExporterCustomizer(BiFunction<? super LogExporter, ConfigProperties, ? extends LogExporter> exporterCustomizer);
```

Would that satisfy customization requirements you have?

**Comment by wallezhang** [comment]
Yes, SPI interface caused me confusion. So the `SdkTracerProviderConfigurer` SPI will be removed in the future, right?

**Comment by jack-berg** [comment]
`SdkTracerProviderConfigurer` will continue to be supported because it's in a stable module. Maybe it will be deprecated though.
