### ISSUE TITLE
Pass parentContext to LogProcessor.emit(), similar to SpanProcessor.onStart()

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4147]
E.g. store the context passed in to `LogDataBuilder.setContext()` (and remove `setSpanContext()`), and pass that context along to `LogProcessor.emit()`.

This would enable writing a LogProcessor that adds Baggage attributes to the log telemetry (and probably other use cases).

**Comment by jack-berg** [comment]
@trask I think you can do this today as long as the log processing is happening on the same thread and in the same context as when the log was recorded. I believe we already rely on that assumption for the log4j, logback, and jul appenders. For example [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.17/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/internal/LogEventMapper.java#L115) we just grab the current context.

As far as i can tell, this was really blocked by `LogRecordProcessor` not being able to mutate any data, which has since been fixed. Here's a demo in action:
```
  @Test
  void demonstrateBaggageLogRecordProcessor() {
    InMemoryLogRecordExporter exporter = InMemoryLogRecordExporter.create();
    SdkLoggerProvider loggerProvider =
        SdkLoggerProvider.builder()
            .addLogRecordProcessor(new BaggageLogRecordProcessor())
            .addLogRecordProcessor(SimpleLogRecordProcessor.create(exporter))
            .build();

    Logger logger = loggerProvider.get("foo");

    try (Scope scope = Baggage.empty().toBuilder().put("key", "value").build().makeCurrent()) {
      logger.logRecordBuilder().setBody("hello world!").emit();
    }

    assertThat(exporter.getFinishedLogItems())
        .satisfiesExactly(
            logRecordData -> {
              assertThat(logRecordData)
                  .hasAttributes(Attributes.builder().put("key", "value").build())
                  .hasBody("hello world!");
            });
  }

  private static class BaggageLogRecordProcessor implements LogRecordProcessor {

    @Override
    public void onEmit(ReadWriteLogRecord logRecord) {
      Baggage.current()
          .asMap()
          .forEach(
              (s, baggageEntry) ->
                  logRecord.setAttribute(AttributeKey.stringKey(s), baggageEntry.getValue()));
    }
  }
```

**Comment by trask** [comment]
> As far as i can tell, this was really blocked by LogRecordProcessor not being able to mutate any data, which has since been fixed.

👍 

I think it may still be good to pass in the `Context` since some people prefer explicit context propagation as opposed to using ThreadLocal (though this is not a problem for auto-instrumentation, which relies on ThreadLocal).

**Comment by jkwatson** [comment]
should the blocked:spec label be removed from this issue?

**Comment by jack-berg** [comment]
The Log SDK spec `LogProcesssor#onEmit` method doesn't [currently](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#onemit) include `Context` as an argument. However, the omission is most likely just an oversight and not intentional. Its really a no-brainer to include context as an argument:

- Provides symmetry with [SpanProcessor#onStart](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#onstart)
- Allows context like baggage to be used by processor implementations without needing to rely on implicit context injection. Currently, LogRecordProcessors which wish to operate on context must rely on fetching `Context.current()`, which relies on a couple of assumptions about how the log was recorded and how the processor was invoked.

There's an [effort](https://github.com/open-telemetry/opentelemetry-specification/issues/2911) to try to identify / resolve the remaining issues needed to stabilize logs, and this specific topic was included: "Consider the need for passing context as a parameter to LogRecordProcessor (from @jack-berg)". I'll be making a PR to the spec with the change, and anticipate folks will agree, so its just a matter of timing of whether to push forward with this now or wait.
