### ISSUE TITLE
AwsXrayPropagator fails to extract SpanId for actual HTTP header

### ISSUE THREAD

**Issue by middlewareman** [open-telemetry/opentelemetry-java#4259]
**Describe the bug**
AwsXrayPropagator fails to extract Context for actual HTTP header 
`X-Amzn-Trace-Id: Root=1-622422bf-59625fe25708d4660735d8ef`.

**Steps to reproduce**
AwsXrayPropagatorTest:
```java
  @Test
  void extract_actualTraceId() {
    Map<String, String> carrier = new LinkedHashMap<>(1);
    // Actual header captured:
    carrier.put("X-Amzn-Trace-Id", "Root=1-622422bf-59625fe25708d4660735d8ef");

    Context context = xrayPropagator.extract(Context.current(), carrier, getter);
    assertThat(context).as("Context should not be root")
        .isNotEqualTo(Context.root()); // BOOM!

    SpanContext spanContext = getSpanContext(context);
    assertThat(spanContext).as("SpanContext should be valid")
        .satisfies(SpanContext::isValid);
    assertThat(spanContext).as("SpanContext should not be equal to invalid")
        .isNotEqualTo(SpanContext.getInvalid());
  }
```

**What did you expect to see?**
I expected `xrayPropagator.extract` to return a non-root Context.

**What did you see instead?**
 `xrayPropagator.extract` returns the root Context.

**What version and what artifacts are you using?**

> io.opentelemetry:opentelemetry-api:1.12.0
> io.opentelemetry:opentelemetry-context:1.12.0
> io.opentelemetry:opentelemetry-exporter-otlp-common:1.12.0
> io.opentelemetry:opentelemetry-exporter-otlp-trace:1.12.0
> io.opentelemetry:opentelemetry-extension-aws:1.12.0
> io.opentelemetry:opentelemetry-sdk:1.12.0
> io.opentelemetry:opentelemetry-sdk-common:1.12.0
> io.opentelemetry:opentelemetry-sdk-extension-aws:1.12.0
> io.opentelemetry:opentelemetry-sdk-logs:1.12.0-alpha
> io.opentelemetry:opentelemetry-sdk-metrics:1.12.0-alpha
> io.opentelemetry:opentelemetry-sdk-trace:1.12.0
> io.opentelemetry:opentelemetry-semconv:1.12.0-alpha
> io.opentelemetry.contrib:opentelemetry-aws-xray:1.11.0

I use SBT, but I can reproduce the problem with the unit test above directly in the `opentelemetry-java` build. 

**Environment**
Compiler: Amazon Corretto 11.0.14
OS: Windows 10 Version 21H1
Runtime (if different from JDK above): -
OS (if different from OS compiled on): -

**Additional context**
It seems that no `SpanId` can be extracted from the header, and the "default" `SpanId` `"0000000000000000"` is considered invalid.

**Comment by anuraaga** [comment]
@willarmiros

**Comment by willarmiros** [comment]
Hi @middlewareman,

This is a known issue where if the X-Ray trace header spec allows a trace context containing only the trace ID but no span ID, however when such a context is parsed into an OpenTelemetry context it's treated as invalid and a new one is generated instead. Is that a correct description of the behavior?

To be clear on expected behavior: in this case you would like a context to be created with the trace ID `1-622422bf-59625fe25708d4660735d8ef`, and no span ID (e.g. so that you can generate a span as part of this trace later)?

**Comment by middlewareman** [comment]
Hi @willarmiros,

Yes, I intend to create my own spans from an OpenTelemetry Context retrieved by AwsXrayPropagator.

**Comment by willarmiros** [comment]
Got it, thanks for the info! For additional context, the only way that these half-complete trace headers are added is through ALB (or API gateway, which uses ALB under the hood). This problem is tracked here: https://github.com/aws-observability/aws-otel-collector/issues/738

We are trying to work with the ALB team to add complete trace contexts, but have no ETA on this so far.

**Comment by kubawach** [comment]
@willarmiros what do you think about adding the proposed ^^ warning to the XRay header extractor? Then we could close this issue.

**Comment by willarmiros** [comment]
I agree that warning at least describes the current (not-ideal) behavior to users, which is the best we can do for now.
