### ISSUE TITLE
Append unit to prometheus metric names

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4390]
The spec [requires](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#metric-metadata-1) that unit be appended to the metric name as a suffix. We don't do that anywhere today. I believe that would represent a breaking behavior change for prometheus users as their metric names would change when unit is present. 

Still, would be good to do that soon to minimize the impact.

_Originally posted by @jack-berg in https://github.com/open-telemetry/opentelemetry-java/pull/4386#discussion_r852442963_

**Comment by jack-berg** [comment]
Related [spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2497).

**Comment by psx95** [comment]
I would like to take this up, if that's ok. 
@jack-berg could you assign this to me ?

**Comment by psx95** [comment]
Just to confirm since the link in the original description is broken, [Prometheus and OpenMetrics Compatibility](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md) is the portion of the spec that needs to be followed to address this issue, correct ?

**Comment by dashpole** [comment]
That is correct.  See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#metric-metadata-1 for unit guidance.

**Comment by psx95** [comment]
Based on the [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/README.md#instrument-units) in the spec document, I just wanted to confirm as to what should be the approach if user has a unit named `{packets}`, we cannot append this to the metric name, since it would violate the regex defined in the spec. 

So in this case, we do drop the unit altogether, meaning no-op, is this correct ?

**Comment by dashpole** [comment]
That is considered unitless in prometheus, so we should drop units (at the portion within the brackets) with `{}`.  I'll update the spec to more fully describe the mapping.
