### ISSUE TITLE
SDK: Make InMemoryExporter more testing friendly

### ISSUE THREAD

**Issue by carlosalberto** [open-telemetry/opentelemetry-java#440]
At the moment, `InMemoryExporter` exposes the `Span` data as the low-level protobuf representation - which is nice if you want to inspect what you want right before you move it through the wire, but not truly friendly if you want to write tests against it.

For example, for testing a given Trace Id, you need to get the Protobuf `ByteString`, get its underlying `byte[]`, create a `TraceId`, and then compare it (unless you inspect the bytes directly yourself). Same for Span Id, and it gets funkier with Links, for example. And I honestly think it's going to be rather annoying to be writing these conversions back and forth to test things.

I had previously used an in-memory `Tracer` saving stuff as `SpanData`, which proved this data type was friendly enough. If not using this specific data type, another similar one would be fine.

Opinions on this?

cc @bogdandrutu

**Comment by bogdandrutu** [comment]
I think the major concerns are around IDs, all the other fields are Strings or Event or Attributes. We have two options:

Return a TestingSpan that wraps the proto representation and exposes `assertHas(TraceId /* from API*/ traceId)`, `assertHas(Event /* from API*/ event)`.

Other option is to expose helper functions traceIdFromProto, spanIdFormProto etc. in a testing artifact.

In all these cases I think we should have a testing artifact that has all these functionality including a setup and cleanup method that does the right thing.

Just for your testbed, probably for IDs I would suggest you use a helper class `TraceID traceIdFromProto(span.getTraceId())`. We will address probably a bit later the testing artifact, but I think it is better to use the SDK in your tests because that gives us confidence in the SDK as well.

**Comment by carlosalberto** [comment]
> Just for your testbed, probably for IDs I would suggest you use a helper class TraceID traceIdFromProto(span.getTraceId()). We will address probably a bit later the testing artifact, but I think it is better to use the SDK in your tests because that gives us confidence in the SDK as well.

Fair enough. I had already started doing this, so I only need to wrap up the effort ;)

**Comment by carlosalberto** [comment]
Closing. Will open a new ticket about creating an artifact to expose the `InMemoryExporter` for testing purposes.
