### ISSUE TITLE
Change autoconfigure JVM shutdown hook to call flush only?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#4416]
Currently, the autoconfigure module registers a JVM shutdown hook that calls `shutdown()` on the processors/exporters.

I believe that a full `shutdown()` is not needed on JVM shutdown, and it would be just as good (and faster) to call `flush()`.

**Comment by jack-berg** [comment]
It's not needed because all the threads that are doing exporting are daemon threads?

If so, is that guaranteed to be true? For tracing, calling `SdkTracerProvider#shutdown()` calls `SpanProcessor#shutdown()`. What if an implementation is doing background work on non-daemon threads? Similar story for logs. Metrics don't allow custom readers (for now), but `PeriodicMetricReader` allows you to configure your own executor.

**Comment by trask** [comment]
ya, I discussed this with @anuraaga at one point (after I submitted this issue), and he didn't feel like we should change this behavior, I'll close this, you bring up good points also
