### ISSUE TITLE
Unit should be left empty if invalid values are provided

### ISSUE THREAD

**Issue by arminru** [open-telemetry/opentelemetry-java#4418]
With #4384 the unit is set to `1` if the user/instrumentation-provided value is invalid.

In https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-unit the spec says:

> If the unit is not provided or the unit is null, the API and SDK MUST make sure that the behavior is the same as an empty unit string.

I think the default of "empty string" should be used as a fallback for invalid values as well.

cc @jack-berg

**Comment by arminru** [comment]
@jack-berg @jkwatson Should this be qualified as a bug?
I don't think replacing any explicitly provided value found to be invalid with `1` is correct since this has a different meaning. Dropping it so it's unset/empty would make more sense to me.

**Comment by jkwatson** [comment]
I think empty string makes more sense as well. @jack-berg I think you put in the '1', but I don't recall the reasoning behind that choice.

**Comment by jack-berg** [comment]
The `1` was previously the default value, aka the value that was included if no unit was specified. I set the unit to `1` when the unit was invalid so that it aligned with the default. 

The default should probably be changed from `1` to empty, and the value when the unit is invalid should be aligned.
