### ISSUE TITLE
Data may lose if multiple propagators write the same header to the carrier?

### ISSUE THREAD

**Issue by jiwen624** [open-telemetry/opentelemetry-java#4463]
This question is about the propagator: `io.opentelemetry.context.propagation.TextMapPropagator`. I'm not sure if it's by design so I didn't open a `Bug` ticket.

**Scenario**:  multiple propagators are configured and two (or more) of them inject the same header (for example, `tracestate`. A propagator may need to add/update its part while keep the other parts untouched. ) to the carrier.

The problem is in `io.opentelemetry.context.propagation.TextMapPropagator`'s `inject` method we cannot access the `getter` of the `carrier`, which means we cannot get the existing header value (an upstream propagator may have injected the same header to the carrier already). If the downstream propagator injects the same header, the update/inject from the upstream propagator may be lost. For this specific `tracestate` header, our propagator currently get it from the span context. However, as the span context is immutable, the upstream propagator doesn't have a chance to update it in the context either.

Is it an expected behaviour or it's a place where the propagator interface can be improved a little bit?

**Comment by jkwatson** [comment]
This is definitely by design (and as specified by the otel spec). If you need to chain propagators to have multiple injectors manipulating the same header, you're outside of what we're currently supporting. I'm guessing you could probably implement your own propagator that did this job, but without understanding why you want two propagators to manipulate the same header, I would have a hard time suggesting the right way to do it.

**Comment by jiwen624** [comment]
Thanks! @jkwatson I also see it in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/context/api-propagators.md#inject

I'm closing this issue now.
