### ISSUE TITLE
mtls Client key file does not follow the specification to read pem file, it reads der instead

### ISSUE THREAD

**Issue by pureklkl** [open-telemetry/opentelemetry-java#4528]
**Describe the bug**
while the specification said the OTEL_EXPORTER_OTLP_CLIENT_KEY will read pem format, it actually read DER only which is the binary form of pem. If you also feed with pem file, you will get wrong key format error.
Also the code only read PCKS8 encoded key which should be mentioned in the readme at least, PCKS1 is still widely being used.

**Steps to reproduce**
OTEL_EXPORTER_OTLP_CLIENT_KEY=aPEMKeyfile.pem

**What did you expect to see?**
should read pem file without error, supporting DER is something good to have.

**What did you see instead?**
it cannot read pem file.

**What version and what artifacts are you using?**
v0.13.1, while the code did not change since then

**Environment**
opentelemetry operator

**Additional context**
the spec and code are from the the same issue, so we can also change the spec either, but some other languages support both.

**Comment by anuraaga** [comment]
Hi @pureklkl - that environment variable was added in v1.13.0. Can you confirm the version you are using, which I guess is not v0.13.1?

**Comment by anuraaga** [comment]
@pureklkl In #4529 I have added a check to verify our integration tests are indeed using PEM format, not DER format. Could the problem you saw just be the use of PKCS1?

Unfortunately we won't be able to support PKCS1 since we can't use bouncycastle https://stackoverflow.com/questions/41934846/read-rsa-private-key-of-format-pkcs1-in-java
