### ISSUE TITLE
Extract `ConfigProperties` to a separate module so that it can be used in `instrumentation-api`

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java#4563]
**Is your feature request related to a problem? Please describe.**
We'd like to use `ConfigProperties` in the instrumentation code too, and get rid of the duplicate `Config` functionality. As it is now, `ConfigProperties` lives in the `autoconfigure-spi` module, which we cannot use in `instrumentation-api` because it has SDK dependencies.

**Describe the solution you'd like**
We could extract `ConfigProperties` to a separate `opentelemetry-config` module that does not depend on anything else; and use it both in the SDK autoconfigure and `instrumentation-api` (and all instrumentations too).

**Describe alternatives you've considered**
Moving `ConfigProperties` to `opentelemetry-api` is a no-go; we don't really want to have a duplicate `Config` either.

**Additional context**
Related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6202

**Comment by mateuszrzeszutek** [comment]
Hmm, if we change the package name (which now contains words `autoconfigure`, `sdk` which might not suit the instrumentation use case) then, it would be a breaking change, unless we preserve the old interface and make a bridge implementation to the new one.

**Comment by anuraaga** [comment]
Yeah if we go ahead with the extraction we'd definitely need the extraction.

**Comment by jack-berg** [comment]
Couple of options I see:
1. Split it to `opentelemetry-config`, keep the package name as is.
2. _Copy_ it to `opentelemetry-config`, changing its package name to better reflect its intended use. Deprecate `autoconfigure-spi` version and have it extend the `opentelemetry-config` version. 
3. Do nothing, agent uses `autoconfigure-spi` version. 
4. Do nothing, agent defines duplicate `Config`.

I think option 2 is probably best long term. In addition to the agent being able to benefit from it, there are various places in the SDK that would benefit from reading from `ConfigProperties`, but don't because they can't take a dependency on `autoconfigure-spi` (e.g. [DebugConfig](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/debug/DebugConfig.java)). Downsides are maintaining a deprecated interface in `autoconfigure-spi` for a while, and having another artifact.

**Comment by trask** [comment]
we discussed in office hours and @jkwatson had a good thought that in the future we'll probably want a richer configuration data structure (e.g. for yaml-based config) that would cover both sdk and instrumentation configuration, and that would be a good time to introduce a new config API.

and so in the meantime, the current thought is not to touch the autoconfigure ConfigProperties.

I'll open a new issue in the instrumentation repo to discuss next steps there, but feel free to post here if you think we should still consider changes in autoconfigure ConfigProperties.

**Comment by mateuszrzeszutek** [comment]
I think this can be closed now; we're going to have a separate, internal (for now) agent-only config that simply forwards all calls to `ConfigProperties`.
