### ISSUE TITLE
Breaking change introduced in SpanData, ReadableSpan interfaces

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#4639]
This PR: https://github.com/open-telemetry/opentelemetry-java/pull/4256 Introduced new methods to public interfaces without providing default implementations. This is a breaking change, and hence a bug. We need to add default implementations ASAP and issue a patch release to correct this.

**Comment by jack-berg** [comment]
I see additional methods without default implementation added to `ReadableSpan` and `SpanData`. 

There's also an abstract method added to the autovalue builder [TestSpanData.Builder#setInstrumentationScopeInfo](https://github.com/open-telemetry/opentelemetry-java/pull/4256/files#diff-2f2310a89c0ebdd149591303e8c57b1e7e245064f4cd81491dc84033f55300e4R134-R135), but I believe we don't have to add a default implementation because the builder already has package private methods that prevents users from implementing their own.

**Comment by jkwatson** [comment]
The user who reported this says they were able to workaround, so perhaps we can put off releasing a patch until we have a user who needs it. We should still add the default methods, I think, so it isn't a problem moving forward.
