### ISSUE TITLE
Publish SNAPSHOT builds

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java#467]
We should publish snapshot builds to a snapshot repo (like Jfrog's).  Here is documentation on how to do that: https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org

**Comment by ohpauleez** [comment]
Food for thought:

What about cutting stable "alpha" releases to maven central, instead of SNAPSHOT versions.
For example, you can release "1.0.0-alpha1", from there you could release "1.0.0-RC1" for release candidate versions, and finally release "1.0.0".

This let's people work against stable targets as they sort out integration concerns without the release shifting from underneath them.  People can also come back here to report bugs against a stable version instead of the ephemeral SNAPSHOT.

**Comment by carlosalberto** [comment]
@ohpauleez 

We will definitely have stable targets down the road - having snapshots would help developers to try out the ongoing effort/features.

And yes, we will also have (eventually, that is) alpha releases, as well as release candidates.

**Comment by bogdandrutu** [comment]
@carlosalberto can you take this issue and setup snapshot releases?

**Comment by carlosalberto** [comment]
I will take it, yes.

**Comment by carlosalberto** [comment]
This is done as part of #523 - feel free to re-open if/as needed ;)
