### ISSUE TITLE
api metrics missing toString/get implementation

### ISSUE THREAD

**Issue by amouhadi** [open-telemetry/opentelemetry-java#4829]
All classes under `io.opentelemetry.api.metrics` are missing toString or any get method. e.g:(DoubleCounter, DoubleGaugeBuilder, DoubleHistogram, DoubleUpDownCounter, DoubleUpDownCounterBuilder, LongCounter, LongGaugeBuilder, LongUpDownCounter, LongUpDownCounterBuilder, ...) 
After we use the Builder classes and set name, unit, description then there is no way to get the metric name or use toString to get the information about that api metrics. This is becoming more critical each time we need to debug/troubleshoot

**Comment by jkwatson** [comment]
Please submit a PR for this change! Thanks!

**Comment by mkorzeniewski** [comment]
I can not see any way to add `toString` methods to the `io.opentelemetry.api.metrics` package. It contains interfaces which are _contracts_ with no state to describe for the `toString` method.

I assumed the origin of the problem lies in the luck of `toString` method in `io.opentelemetry.sdk.metrics` package because the problem I see is when you create an instance of an `AbstractInstrument` there is only default `toString` method provided.

Now it should be possible to se the following fields `name, unit, description`.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/37160097/197627953-0e995b68-b5d1-4b54-a319-802a1247d243.png">

**Comment by mkorzeniewski** [comment]
Does it resolves the problem somehow? Is a `toString` method needed for Builders? I believe it is always a way to create an instance and then call `toString` method

**Comment by jack-berg** [comment]
The change in #4833 does not add `toString` to the instrument builders. If you feel this is necessary please re-open.

**Comment by mkorzeniewski** [comment]
You can assign me to the new issue you will create.
