### ISSUE TITLE
Why was the annotation @WithSpan moved out

### ISSUE THREAD

**Issue by Emily-Jiang** [open-telemetry/opentelemetry-java#4877]
I just noticed in the release 1.19, the annotation `WithSpan` the `SpanAttribute` was moved to another project, which is in alpha state. I have a few concerns:
1.  Why was the reason of moving these annotationed moved to java-instrumentation? I looked at the issue [6245](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6245), but I did not find out why.
2. Are the annoations stable since they were moved to a unstable project `[opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation)`
3. This move is a breaking change. Should this happen in a minor release.

**Comment by trask** [comment]
hi @Emily-Jiang!

the main reason the annotations were moved to the instrumentation repo is so that they can evolve alongside the instrumentation code, as we found ourselves at a roadblock in #4260

`opentelemetry-java-instrumentation` is not inherently unstable, though the new annotation artifact in the instrumentation repository is currently marked unstable. we have an issue tracking making the new annotation artifact stable: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6494, if you can comment over there it could help move that along

whether this move is a breaking change was discussed over a couple of SIG meetings, and the consensus is summarized in #4729

**Comment by jack-berg** [comment]
I'm going to close this issue. Please feel free to re-open if more information is needed on the stability guarantees!
