### ISSUE TITLE
Why is `AbstractInstrument` not publicly accessible?

### ISSUE THREAD

**Issue by gabroo** [open-telemetry/opentelemetry-java#4878]
I'm trying to write some helper class to make it easier to record metrics in our application. It would be nice to be able to define functions that accept [`AbstractInstrument`](https://github.com/open-telemetry/opentelemetry-java/blob/d868eff3e1d63a7d46f5866d676570cc2f2be84a/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/AbstractInstrument.java) as a parameter, but this class isn't publicly accessible. Is there a reason why we can't make it public?

**Comment by jkwatson** [comment]
This is not public because we did not want to have to support this internal implementation detail as a part of our public API. If we were to make it public, we would never be able to remove it or change its API in the future, and this isn't something we're currently comfortable supporting forever.

If you can make a strong case for us making it public, we could consider it.

**Comment by breedx-splk** [comment]
@gabroo Can you give some additional detail about why you're wanting "to make it easier to record metrics"? That is, what about the current APIs is challenging or cumbersome or confusing?

**Comment by jack-berg** [comment]
To add a little more information, `AbstractInstrument` is part of the SDK. The SDK is for configuring how data captured through the APIs is processed, but isn't intended to be used directly. 

Maybe it would be useful to have a common supertype of all the metric instrument interfaces (DoubleCounter, LongCounter, DoubleHistogram, LongHistogram, etc), but as of now there isn't any shared behavior across all instruments. Without shared behavior, what would you hope to gain from defining a supertype?

**Comment by gabroo** [comment]
I suppose my assumption is that all the synchronous instruments share the behavior of recording measurements on-demand. For instance, `LongCounter.add(Long)` and `LongHistogram.record(Long)` both seem to be implementations of a hypothetical `AbstractInstrument<Value>.measure(Value)`.

I wanted to abstract this behavior into a single type. Is this an incorrect interpretation of the behavior?

**Comment by jack-berg** [comment]
The names of those methods and their semantics are different:

- Long/DoubleUpDownCounter has an add method, which supports positive and negative values
- Long/DoubleCounter has an add method which only supports non-negative values.
- Long/DoubleHistogram has a record method which currently only supports non-negative values, but will likely change to support them in the future. 

The method name record in histogram is different from the counters because counters count things, and its natural to think of adding to a counter. Recording to a histogram does a variety of things: it increments a counter, it adds to a sum, it updates the min / max if needed, and increments the relevant bucket.

I think its reasonable for you to define an `AbstrctInstrument` class with a measure method which delegates to add or record based on whether the instrument is a counter or histogram. However, we chose not to do that because calling the methods add or record confers information about the semantics of the method that a generic name like measure does not. We could add a measure method and have the record and add methods just be syntactic sugar. But that increase in API surface area needs to have a strong justification in usability.

Adding shared behavior in a supertype implies that you want to do things like create `Collection<AbstractInstrument>` and do some common processing on a heterogenous mix of instrument types. Do you have examples where that would be useful?
