### ISSUE TITLE
Add cardinality configuration option to sdk autoconfigure

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java#5639]
**Is your feature request related to a problem? Please describe.**
Currently the default metricReaders registered using AutoConfiguredOpenTelemetrySdkBuilder are all set to use the default cardinality limit selector, I'd like to be able to set cardinality options as config properties.

**Describe the solution you'd like**
Add cardinality configuration logic to MeterProviderConfiguration in the autoconfigure module

**Describe alternatives you've considered**
Re-register the already registered readers using MeterProviderCustomizer.

**Additional context**
I'd like to contribute this.

**Comment by akats7** [comment]
@jack-berg

**Comment by jack-berg** [comment]
This is tricky.. The natural thing to do would be to add support for a new system property / environment variables, i.e. `OTEL_METRICS_EXPORTER_CARDINALITY_LIMIT`. However, there's a [moratorium](https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503) while we work out a more future facing file based configuration strategy. That file configuration strategy would be the place where cardinality limit configuration would find a permanent home. However, it would be nice if we (otel java) could provide some temporary bridge for the time being, since as you've found out, its pretty challenging to try to set cardinality limits with autoconfigure.

@jkwatson what do you think about adding a `OTEL_JAVA_EXPERIMENTAL_*` environment variable to set the desired cardinality limit? For simplicities sake, we could have it set a single cardinality limit for all instruments. Cardinality limits can vary as a function of instrument kind, but encoding that into a temporary environment variable feels like overkill. The `*_JAVA_EXPERIMENTAL_*` signifies this is experimental and is likely to go away / change in the future, and is specific to the java ecosystem (i.e. don't go looking for this in otel js, go, etc).

**Comment by jkwatson** [comment]
totally fine with an experimental env var. 👍🏽
