### ISSUE TITLE
Allow Log API to record structured body

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#5847]
The Log API currently only allows the body field to be `String`, but the [spec says](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body):

> However, a structured body SHOULD be used to preserve the semantics of structured logs emitted by Third-party Applications. Can vary for each occurrence of the event coming from the same source. This field is optional.

We don't support any body types besides string because we haven't had use cases. However, in the 9/21/23 Java SIG we discussed how the Logback / Log4j appenders deal with structured log records and possible collisions with attributes from MDC. If log body could hold the structured message from logback / log4j (instead of putting in attributes), then mdc attributes would not have the possibility of overlapping with fields from the structured message.

Note, the log body is an `Any` type on the wire and we should make sure that whatever data structure we introduce to represent structured body reflects `Any` semantics.

**Comment by scheler** [comment]
On Android, there's a use-case for sending screenshots.  Can we include adding the support for `bytes` type as part of `any` for body?   I am assuming adding `bytes_value` to attribute values is far harder due to its wider use, than body which is only in LogRecords, hence making the case for this request.

**Comment by bidetofevil** [comment]
Should we wrap some more semantic convention/definition to define what this byte-string serializes to? The inability to know what the underlying data that we're dealing with makes this difficult to handle generically, and defining some structure around it seems like a good idea.

**Comment by scheler** [comment]
@bidetofevil  Yes, that will be required and could be specified via attributes. Maybe we could do that in a separate issue / pr, and this issue could focus on the generic API support.

**Comment by bryce-b** [comment]
I think that the original use case of the Logs signals is outside of scope for mobile. That use case being: collecting all logs from the device and sending them to the collector. Mobile apps will very quickly outpace the number of instances commonly seen service side, if the app has any sort of popularity, and thus inundate the collector with an overload of log data. 
Otherwise, I don't have a strong opinion either way here.

**Comment by bryce-b** [comment]
Additionally, I think that sending screenshots would be a useful feature to provide; however swift doesn't support sending binary data at this point.
