### ISSUE TITLE
Senders do not guarantee delivery of spans being processed while shutdown

### ISSUE THREAD

**Issue by ricardo-mestre** [open-telemetry/opentelemetry-java#6160]
**Describe the bug**
All sender do not gracefully shutdown, instead they cancel everything in process. They mostly return a completable of success or forcefully close everything

**Steps to reproduce**
It's easy to check with a small main method that calls the telemetry shutdown just after closing some spans. Those won't get exported

**What did you expect to see?**
The already closed and queued spans should reach destination before closing the sender, any new span should not be accepted

**What did you see instead?**
All spans in queue were discarded

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-api`, `OkHttpSender`
Version: 1.34.0

**Comment by andrebrait** [comment]
We just found that `JDKSender` also does not allow the pending spans time to be exported. All of them also do not give any way to wait for that, as they all immediately return success.

See the following pieces of code: 

https://github.com/open-telemetry/opentelemetry-java/blob/4407ee72d626449dba7baecc86ef8c444322a0c6/exporters/sender/okhttp/src/main/java/io/opentelemetry/exporter/sender/okhttp/internal/OkHttpHttpSender.java#L154-L159

https://github.com/open-telemetry/opentelemetry-java/blob/4407ee72d626449dba7baecc86ef8c444322a0c6/exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java#L307-L310

https://github.com/open-telemetry/opentelemetry-java/blob/4407ee72d626449dba7baecc86ef8c444322a0c6/exporters/sender/grpc-managed-channel/src/main/java/io/opentelemetry/exporter/sender/grpc/managedchannel/internal/UpstreamGrpcSender.java#L88-L94

I suggest either:

1. Not cancelling all pending jobs on the dispatcher
2. Overloading `shutdown` to pass a timeout argument
3. Switching from `shutdownNow()` to `shutdown()` + `awaitTermination(long, TimeUnit)`

or:

1. Not cancelling all pending jobs on the dispatcher
2. Keep track of submitted jobs and the returned `Future` objects.
3. Switching from `shutdownNow()` to `shutdown()`
4. Create a `CompletableResultCode` that completed when all pending jobs complete, so it can be used upstream for e.g. joining, by e.g. `SpanProcessor#close()` or `SdkTracerProvider#close()`

**Comment by jack-berg** [comment]
Can you tell me a little bit more about your use case?

In most cases it shouldn't matter than the OTLP SpanExporter implementations of #shutdown evict threads immediately because shutdown is normally called by `BatchSpanProcessor#shutdown`. When `BatchSpanProcessor` is shutting down, it flushes spans and synchronously waits for SpanExporter#export to complete. So SpanExporter shouldn't have any threads left exporting spans by the time BatchSpanProcessor calls `SpanExporter#shutdown`.

I wrote a little test with some print statements to demonstrate this. The test uses a contrived SpanExporter implementation which is made to artificially block the calling thread on both `SpanExporter#export` and `SpanExporter#shutdown`. When you call `BatchSpanProcessor#shutdown`, you see the following sequence:
```
processor#shutdown - started
processor#flush
exporter#export - started
exporter#export - complete
exporter#shutdown - started
exporter#shutdown - complete
processor#shutdown - completed
```
Notice how `SpanExporter#exporter` completes before `SpanExporter#shutdown` is started.

**Comment by andrebrait** [comment]
@jack-berg that's technically correct, but the waiting isn't actually performed because `SpanExporter#shutdown()` (I mean, the mentioned implementations) just cancels all queued items and immediately returns a success. So even if the `SpanProcessor.close()` is joining on the returned `CompletableResultCode`, it won't actually wait for anything.

Our use-case is a Java job that's launched from a shell script. It had to be manually instrumented and we noticed the last few spans that are ended right before we call `close()` on the SDK are never exported. When investigating why, we realized the `SpanData` was actually being sent to the `SpanExporter` by the `SpanProcessor`, but they were immediately canceled by the logic on `SpanExporter#shutdown()` before the HTTP request was sent.

So there are two issues at play here:

1. The immediate cancellation of all queued jobs on the `SpanExporter`
2. The immediate return of a completed `CompletableResultCode` that makes it impossible to actually wait for any pending exports to finish

**Comment by andrebrait** [comment]
Flushing merely sends the remaining batched `SpanData` to the `SpanExporter`, but the subsequent call to `SpanExporter#shutdown()` will cancel them faster than they can be exported, since there's no real wait.

**Comment by andrebrait** [comment]
I'll see if I can craft an example for you until Monday or so.

**Comment by andrebrait** [comment]
Errata: the `HttpSender#shutdown()` is what actually cancels the exports. 

I ended up conflating the sender and the exporter in my previous comments, but that's about the same thing, functionally speaking, because one just calls the other.

**Comment by jack-berg** [comment]
> Flushing merely sends the remaining batched SpanData to the SpanExporter, but the subsequent call to SpanExporter#shutdown() will cancel them faster than they can be exported, since there's no real wait.

There is a wait tho. BatchSpanProcessor will block for `SpanExporter.export(..).join(..)` (it will wait for the configurable exporter timeout, which defaults to 30s) to finish before calling SpanExporter#shutdown.

**Comment by andrebrait** [comment]
> There is a wait tho. BatchSpanProcessor will block for `SpanExporter.export(..).join(..)` (it will wait for the configurable exporter timeout, which defaults to 30s) to finish before calling SpanExporter#shutdown.

Ok, I went through the entire chain again and indeed, there would be a wait due to the `HttpExporter#export(..)` returning a `CompletableResultCode` that only completes when there's either an error or a success on the `HttpSender` (via the two callbacks it receives as arguments). 

And indeed, the `BatchSpanProcessor` does flush first and that should create a wait if the result is joined. So it should indeed be waiting, as you described.

**Comment by ricardo-mestre** [comment]
Thanks for clarifying this. I'm closing this issue since the description doesn't describe the current shutdown order

**Comment by andrebrait** [comment]
@ricardo-mestre I think now that the Span I found on the queue during `shutdown()` was produced by another thread and it was closed between the flush and the shutdown. That could explain that particular observation then.

**Comment by jack-berg** [comment]
I realize that in [this comment](https://github.com/open-telemetry/opentelemetry-java/issues/6160#issuecomment-1901154312) I talked about an example I wrote and its output, but never provided a link to the source code 🤦.

Here's the link in case anyone is interested in seeing how this works with an example: https://github.com/jack-berg/opentelemetry-java/commit/7b0bdb793f60a773f2902331b72c89729a060bdc
