### ISSUE TITLE
Benchmark default SDK BatchSpanProcessor performance

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#790]

**Comment by andrewhsu** [comment]
from the java sig mtg today, sounds like what is looked for is an automated benchmark job run on merge to master

**Comment by jsuereth** [comment]
There is a benchmark for BatchSpanProcessor in place ().  It *looks* sufficient in that if you compare it to the simple-span-processor benchmark you can make decisions.

Post 1.0 - I'd like to shore up the JMH story to produce an output report that is consumable documentation (or easy-to-turn-into-markdown-consumable-documentation).

I think this bug is no longer a blocker for 1.0.  You can mark it as closed, or I'll update the name to denote that I'd like to (mostly) automate generating a result report in markdown for the documentation of this API/SDK.

**Comment by jkwatson** [comment]
Thanks for digging in, @jsuereth ! I will close this, and we can create new issues/PRs for the work you're proposing.
